from typing import TypedDict, List, Annotated, Literal, Optional
import operator
import re
from urllib.parse import urlparse

from dotenv import load_dotenv
from pydantic import BaseModel, Field, ValidationError

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.messages import SystemMessage, HumanMessage
from langchain_community.tools.tavily_search import TavilySearchResults

from langgraph.graph import StateGraph, START, END


# ============================================================
# 1. ENVIRONMENT
# ============================================================

load_dotenv()


# ============================================================
# 2. CONFIGURATION
# ============================================================

MODEL_NAME = "gemini-3.1-flash-lite"

# IMPORTANT:
# Only this many useful sources are sent to the evidence
# synthesizer and later writing stages.
MAX_EVIDENCE_SOURCES = 12

# Research breadth. We can collect more than 12 raw results,
# rank them locally, and only send the best 12 to Gemini.
MAX_RESEARCH_QUERIES = 10
TAVILY_RESULTS_PER_QUERY = 4

# Keep snippets compact so prompts do not become unnecessarily
# large.
MAX_SNIPPET_CHARS = 900

# Sequential workers are intentional. Five simultaneous Gemini
# calls can cause provider-side rate-limit spikes.
MIN_SECTIONS = 5
MAX_SECTIONS = 7


# ============================================================
# 3. LLM
# ============================================================

llm = ChatGoogleGenerativeAI(
    model=MODEL_NAME,
    temperature=0.7,
)


# ============================================================
# 4. PYDANTIC SCHEMAS
# ============================================================

class Task(BaseModel):
    """
    Represents one section/task of the blog.
    """

    id: int

    title: str

    goal: str = Field(
        ...,
        description=(
            "One sentence describing what the reader should "
            "be able to do or understand after this section."
        ),
    )

    bullets: List[str] = Field(
        ...,
        min_length=3,
        max_length=6,
        description=(
            "3–6 concrete, non-overlapping subpoints "
            "to cover in this section."
        ),
    )

    target_words: int = Field(
        ...,
        description="Target word count for this section.",
    )

    section_type: Literal[
        "intro",
        "core",
        "examples",
        "checklist",
        "common_mistakes",
        "conclusion",
    ] = Field(
        ...,
        description="Type of the blog section.",
    )

    brief: str = Field(
        ...,
        description="What this section should cover.",
    )

    tags: List[str] = Field(
        default_factory=list,
        description="Important tags/topics for this section.",
    )

    requires_research: bool = Field(
        default=False,
        description="Whether this section requires fresh research.",
    )

    requires_citations: bool = Field(
        default=False,
        description="Whether outside-world claims need citations.",
    )

    requires_code: bool = Field(
        default=False,
        description="Whether this section must contain a code example.",
    )


class Plan(BaseModel):
    """
    Complete blog plan generated by the orchestrator.
    """

    blog_title: str

    audience: str = Field(
        description="Who this blog is made for.",
    )

    tone: str = Field(
        description=(
            "Writing tone, for example practical, crisp, "
            "technical, beginner-friendly, etc."
        ),
    )

    blog_kind: Literal[
        "tutorial",
        "news_roundup",
    ] = Field(
        default="tutorial",
        description="The overall type of the blog.",
    )

    constraints: List[str] = Field(
        default_factory=list,
        description="Important constraints that apply to the blog.",
    )

    tasks: List[Task] = Field(
    ...,
    min_length=MIN_SECTIONS,
    max_length=MAX_SECTIONS,
    description=(
        "Dynamically chosen blog sections/tasks. "
        "Must contain between 5 and 7 sections."
    ),
    )


class RouterDecision(BaseModel):
    """
    Decision produced by the routing node.
    """

    needs_research: bool

    mode: Literal[
        "closed_book",
        "hybrid",
        "open_book",
    ]

    queries: List[str] = Field(
        default_factory=list,
        max_length=10,
    )


class EvidenceItem(BaseModel):
    """
    One research source.
    """

    title: str

    url: str

    published_at: Optional[str] = None

    snippet: Optional[str] = None

    source: Optional[str] = None


class EvidencePack(BaseModel):
    """
    Collection of research sources.
    """

    evidence: List[EvidenceItem] = Field(
        default_factory=list,
        max_length=MAX_EVIDENCE_SOURCES,
    )


# ============================================================
# 5. LANGGRAPH STATE
# ============================================================

class ChatState(TypedDict):
    """
    Shared state used by the LangGraph workflow.
    """

    topic: str

    mode: str

    needs_research: bool

    queries: List[str]

    evidence: List[EvidenceItem]

    plan: Optional[Plan]

    sections: Annotated[
        List[tuple[int, str]],
        operator.add,
    ]

    final_md: str


# ============================================================
# 6. GEMINI RESPONSE HELPERS
# ============================================================

def _extract_response_text(response) -> str:
    """
    Normalize LangChain/Gemini response content into plain text.

    Gemini may expose response.content as:
    - a string
    - a list of content blocks
    - a list of strings
    - a list of dictionaries containing text
    - nested content structures
    """

    content = getattr(response, "content", response)

    if isinstance(content, str):
        return content.strip()

    if isinstance(content, list):

        parts: List[str] = []

        def collect(item) -> None:

            if isinstance(item, str):
                if item.strip():
                    parts.append(item)
                return

            if isinstance(item, dict):

                text_value = item.get("text")

                if isinstance(text_value, str):
                    if text_value.strip():
                        parts.append(text_value)
                    return

                nested = item.get("content")

                if isinstance(nested, str):
                    if nested.strip():
                        parts.append(nested)
                    return

                if isinstance(nested, list):
                    for nested_item in nested:
                        collect(nested_item)

                return

        for item in content:
            collect(item)

        return "\n".join(parts).strip()

    return str(content).strip()


def _invoke_structured(schema, messages):
    """
    Invoke Gemini using LangChain structured output.

    Gemini's structured-output path returns a Pydantic object.
    This helper also provides a useful error if the provider
    returns something unexpected.
    """

    structured_llm = llm.with_structured_output(
        schema
    )

    result = structured_llm.invoke(messages)

    if isinstance(result, schema):
        return result

    try:
        return schema.model_validate(result)
    except Exception as exc:
        raise ValueError(
            f"Gemini returned an unexpected structured-output "
            f"format for {schema.__name__}: {result!r}"
        ) from exc


# ============================================================
# 7. ROUTER
# ============================================================

ROUTER_SYSTEM = """
You are a routing module for a general-purpose blog writing agent.

Your job is to analyze the user's requested topic and decide whether the blog
requires external web research.

The blog may cover ANY subject, including but not limited to:
- Technology
- Programming
- Science
- Health and fitness
- Sports
- Education
- History
- Travel
- Business
- Lifestyle
- Hobbies
- General knowledge

Choose "web" when:
- The topic depends on current or changing information.
- The user asks about recent events, current trends, latest information,
  current statistics, recent products, or other time-sensitive facts.
- External evidence would materially improve factual accuracy.
- The topic contains claims that should be supported by recent or authoritative
  sources.

Choose "closed_book" when:
- The topic can be explained accurately without current web information.
- The topic is primarily evergreen knowledge, concepts, explanations,
  educational material, opinions, or general guidance.
- External research is not necessary for producing a useful and accurate blog.

Return ONLY valid JSON matching the required RouterDecision schema.
Do not include markdown, explanations, or additional text.
"""


def router_node(state: ChatState) -> dict:

    topic = state["topic"]

    decision = _invoke_structured(
        RouterDecision,
        [
            SystemMessage(
                content=ROUTER_SYSTEM
            ),
            HumanMessage(
                content=(
                    "User's blog topic:\n"
                    f"{topic}"
                )
            ),
        ],
    )

    queries = [
        q.strip()
        for q in decision.queries
        if isinstance(q, str) and q.strip()
    ][:MAX_RESEARCH_QUERIES]

    return {
        "needs_research": decision.needs_research,
        "mode": decision.mode,
        "queries": queries,
    }


def route_next(state: ChatState) -> str:

    if state["needs_research"]:
        return "research"

    return "orchestrator"


# ============================================================
# 8. TAVILY SEARCH
# ============================================================

def _compact_snippet(value: Optional[str]) -> str:

    if not value:
        return ""

    text = " ".join(
        str(value).split()
    )

    return text[:MAX_SNIPPET_CHARS]


def _domain_from_url(url: str) -> str:

    try:
        return (
            urlparse(url)
            .netloc
            .lower()
            .replace("www.", "")
        )
    except Exception:
        return ""


def _tavily_search(
    query: str,
    max_results: int = TAVILY_RESULTS_PER_QUERY,
) -> List[dict]:
    """
    Run one Tavily search and normalize the output.
    """

    tool = TavilySearchResults(
        max_results=max_results
    )

    results = tool.invoke(
        {
            "query": query
        }
    )

    normalized: List[dict] = []

    for result in results or []:

        if not isinstance(result, dict):
            continue

        url = str(
            result.get("url")
            or ""
        ).strip()

        if not url:
            continue

        normalized.append(
            {
                "title": str(
                    result.get("title")
                    or ""
                ).strip(),

                "url": url,

                "snippet": _compact_snippet(
                    result.get("content")
                    or result.get("snippet")
                    or ""
                ),

                "published_at": (
                    result.get("published_date")
                    or result.get("published_at")
                ),

                "source": (
                    result.get("source")
                    or _domain_from_url(url)
                ),
            }
        )

    return normalized



# ============================================================
# 9. DETERMINISTIC SOURCE RANKING
# ============================================================

def _domain_matches(
    domain: str,
    allowed_domain: str,
) -> bool:
    """
    Return True only when the domain is exactly the allowed
    domain or is a legitimate subdomain of it.

    Examples:

    github.com            -> True
    docs.github.com       -> True
    notgithub.com         -> False
    github.com.evil.com   -> False
    """

    domain = domain.lower().strip(".")
    allowed_domain = (
        allowed_domain
        .lower()
        .strip(".")
    )

    return (
        domain == allowed_domain
        or domain.endswith(
            "." + allowed_domain
        )
    )


def _source_authority_score(item: dict) -> int:
    """
    Lightweight deterministic authority scoring.

    This happens BEFORE the evidence synthesizer, so only the
    best ~10–15 sources ever reach the LLM.
    """

    url = item.get(
        "url",
        "",
    )

    domain = _domain_from_url(
        url
    )

    score = 0

    high_authority_domains = (
        ".gov",
        ".edu",
        "github.com",
        "arxiv.org",
        "openai.com",
        "developers.google.com",
        "ai.google.dev",
        "cloud.google.com",
        "python.org",
        "pytorch.org",
        "tensorflow.org",
        "microsoft.com",
        "aws.amazon.com",
        "anthropic.com",
        "meta.com",
        "developer.mozilla.org",
    )

    reputable_domains = (
        "reuters.com",
        "apnews.com",
        "bbc.com",
        "nytimes.com",
        "techcrunch.com",
        "theverge.com",
        "wired.com",
        "nature.com",
        "arstechnica.com",
    )

    # --------------------------------------------------------
    # High-authority sources
    # --------------------------------------------------------

    if any(
        (
            domain.endswith(suffix)
            if suffix.startswith(".")
            else _domain_matches(
                domain,
                suffix,
            )
        )
        for suffix in high_authority_domains
    ):
        score += 8

    # --------------------------------------------------------
    # Reputable sources
    # --------------------------------------------------------

    if any(
        _domain_matches(
            domain,
            suffix,
        )
        for suffix in reputable_domains
    ):
        score += 5

    # --------------------------------------------------------
    # Freshness
    # --------------------------------------------------------

    if item.get(
        "published_at"
    ):
        score += 1

    # --------------------------------------------------------
    # Useful snippet
    # --------------------------------------------------------

    if item.get(
        "snippet"
    ):
        score += 2

    return score

def _rank_and_select_sources(
    raw_results: List[dict],
    topic: str,
    queries: List[str],
) -> List[dict]:
    """
    Deduplicate, score and select at most 12 sources.

    The full raw Tavily result set is NEVER passed to Gemini.
    """

    query_terms = set(
        re.findall(
            r"\b[a-zA-Z0-9][a-zA-Z0-9_-]{2,}\b",
            " ".join(
                [topic] + queries
            ).lower(),
        )
    )

    unique = {}

    for item in raw_results:

        url = item.get("url", "").strip()

        if not url:
            continue

        if url not in unique:
            unique[url] = item
            continue

        # Keep the richer duplicate.
        old = unique[url]

        if len(
            item.get("snippet", "")
        ) > len(
            old.get("snippet", "")
        ):
            unique[url] = item

    scored = []

    for item in unique.values():

        title = item.get(
            "title",
            "",
        ).lower()

        snippet = item.get(
            "snippet",
            "",
        ).lower()

        text = f"{title} {snippet}"

        overlap = sum(
            1
            for term in query_terms
            if term in text
        )

        score = (
            overlap * 2
            + _source_authority_score(item)
        )

        scored.append(
            (
                score,
                item,
            )
        )

    scored.sort(
        key=lambda pair: (
            pair[0],
            len(
                pair[1].get(
                    "snippet",
                    "",
                )
            ),
        ),
        reverse=True,
    )

    return [
        item
        for _, item in scored[
            :MAX_EVIDENCE_SOURCES
        ]
    ]


# ============================================================
# 10. RESEARCH
# ============================================================

RESEARCH_SYSTEM = """
You are a research synthesizer for technical writing.

You are given ONLY the most useful web sources selected by a
deterministic ranking stage.

Create an EvidencePack from those sources.

Rules:

- Preserve the supplied URLs exactly.
- Only include items with a non-empty URL.
- Do not invent URLs.
- Prefer relevant and authoritative sources.
- Prefer official documentation, company sources,
  research papers, government sources, and reputable
  publications when available.
- Preserve an explicitly supplied publication date.
- Never guess a publication date.
- Keep snippets concise.
- Do not create additional sources.
- Deduplicate by URL.
- Return at most 12 evidence items.

Return only the EvidencePack fields.
"""


def research_node(state: ChatState) -> dict:
    """
    Search Tavily, rank locally, and send ONLY the best 12
    sources to Gemini.
    """

    queries = (
        state.get(
            "queries",
            [],
        )
        or []
    )[:MAX_RESEARCH_QUERIES]

    raw_results: List[dict] = []

    for query in queries:

        try:

            results = _tavily_search(
                query,
                max_results=TAVILY_RESULTS_PER_QUERY,
            )

            raw_results.extend(results)

        except Exception as exc:

            print(
                f"Research failed for query "
                f"'{query}': {exc}"
            )

    if not raw_results:

        return {
            "evidence": []
        }

    selected_sources = _rank_and_select_sources(
        raw_results=raw_results,
        topic=state["topic"],
        queries=queries,
    )

    # IMPORTANT:
    # Only selected_sources (max 12) are passed to Gemini.
    compact_sources = []

    for item in selected_sources:

        compact_sources.append(
            {
                "title": item.get(
                    "title",
                    "",
                ),

                "url": item.get(
                    "url",
                    "",
                ),

                "snippet": item.get(
                    "snippet",
                    "",
                ),

                "published_at": item.get(
                    "published_at"
                ),

                "source": item.get(
                    "source"
                ),
            }
        )

    pack = _invoke_structured(
        EvidencePack,
        [
            SystemMessage(
                content=RESEARCH_SYSTEM
            ),
            HumanMessage(
                content=(
                    "Topic:\n"
                    f"{state['topic']}\n\n"
                    "Selected source candidates "
                    f"(maximum {MAX_EVIDENCE_SOURCES}):\n"
                    f"{compact_sources}"
                )
            ),
        ],
    )

    # Final deterministic URL deduplication + hard cap.
    dedup = {}

    for item in pack.evidence:

        if item.url:

            dedup[
                item.url
            ] = item

    final_evidence = list(
        dedup.values()
    )[
        :MAX_EVIDENCE_SOURCES
    ]

    return {
        "evidence": final_evidence
    }


# ============================================================
# 11. ORCHESTRATOR
# ============================================================

ORCH_MESSAGE = """
You are the senior content strategist and blog planner for a general-purpose
AI blog writing system.

Your job is to create a strong, logical, reader-focused plan for the user's
requested topic.

The blog can be about ANY subject.

IMPORTANT AUDIENCE RULE:
- Assume that the reader is a general audience.
- Determine the appropriate level of explanation from the topic itself.
- Use technical terminology only when it is relevant to the topic.
- If the topic is technical, technical terminology is appropriate.
- If the topic is non-technical, use language appropriate for a general reader.
- Never inject programming, software engineering, developer terminology, or
  technical analogies into a topic unless they are genuinely relevant.

IMPORTANT WRITING RULE:
The goal is to create a useful, accurate, engaging, and logically structured
blog — not to make the content sound unnecessarily sophisticated.

Prefer:
- Clear explanations
- Useful information
- Logical progression
- Appropriate depth
- Concrete examples when useful
- Reader-friendly language
- Topic-specific terminology when relevant

Avoid:
- Unnecessary jargon
- Forced technical terminology
- Forced analogies
- Developer-oriented language for non-technical topics
- Overly complicated explanations
- Generic filler

The structure should be appropriate for the topic rather than following a
fixed technical-blog template.

The overall plan should contain approximately 5–7 meaningful sections when
appropriate, but the exact number may vary if the topic naturally requires
fewer or more sections.

Each section should have:
- A clear, meaningful heading
- A concise description of what the section should cover
- The key information that should be included
- An indication of whether code is actually required

CODE RULE:
Code is OPTIONAL.

Include code only when it is genuinely useful and relevant to the topic.

For programming, software, technical, or other code-related topics:
- Code may be appropriate.
- Include a code example when it improves the explanation.

For non-technical topics:
- Do NOT force code into the blog.
- Set requires_code to false unless there is a genuine reason for code.

RESEARCH RULE:
When research evidence is provided:
- Use the evidence to guide the structure and factual coverage.
- Prioritize authoritative and relevant sources.
- Do not invent facts that are not supported by the available evidence.
- Do not force research into sections where it is not relevant.

QUALITY BAR:
- The plan must directly address the user's topic.
- The plan must make sense for the intended reader.
- Each section should have a distinct purpose.
- Avoid unnecessary repetition between sections.
- Avoid generic sections that could apply to any unrelated topic.
- Technical depth should match the subject and reader.
- Do not introduce concepts merely because they sound advanced.
- Keep the final blog useful and engaging rather than unnecessarily complex.

Create the plan based on the following information.

Topic:
{topic}

Research mode:
{research_mode}

Evidence:
{evidence}

Return the result using the required Plan schema.
"""

def validate_plan(plan: Plan) -> Plan:
    """
    Validate the orchestrator's dynamic blog plan.

    The orchestrator may choose 5, 6, or 7 sections,
    but never fewer than 5 or more than 7.
    """

    task_count = len(plan.tasks)

    if not (
        MIN_SECTIONS
        <= task_count
        <= MAX_SECTIONS
    ):

        raise ValueError(
            f"Plan must contain between "
            f"{MIN_SECTIONS} and {MAX_SECTIONS} sections, "
            f"got {task_count}"
        )

    task_ids = [
        task.id
        for task in plan.tasks
    ]

    if len(set(task_ids)) != len(task_ids):

        raise ValueError(
            "Task IDs must be unique."
        )

    expected_ids = list(
        range(
            1,
            task_count + 1,
        )
    )

    if sorted(task_ids) != expected_ids:

        raise ValueError(
            "Task IDs must be sequential starting from 1. "
            f"Expected {expected_ids}, got {sorted(task_ids)}"
        )

    common_mistakes_count = sum(
        task.section_type
        == "common_mistakes"
        for task in plan.tasks
    )

    if common_mistakes_count != 1:

        raise ValueError(
            "Plan must contain exactly one "
            "'common_mistakes' section."
        )

    return plan


def orchestrator_node(
    state: ChatState,
) -> dict:

    evidence = state.get(
        "evidence",
        []
    )

    # Never pass more than the selected 12 sources.
    evidence_for_prompt = [
        item.model_dump()
        for item in evidence[
            :MAX_EVIDENCE_SOURCES
        ]
    ]

    mode = state.get(
        "mode",
        "closed_book",
    )

    plan = _invoke_structured(
        Plan,
        [
            SystemMessage(
                content=ORCH_MESSAGE
            ),
            HumanMessage(
                content=(
                    f"Topic:\n"
                    f"{state['topic']}\n\n"

                    f"Mode:\n"
                    f"{mode}\n\n"

                    "Evidence "
                    "(ONLY use for fresh claims; "
                    "may be empty):\n"
                    f"{evidence_for_prompt}"
                )
            ),
        ],
    )

    plan = validate_plan(plan)

    return {
        "plan": plan
    }


# ============================================================
# 12. WORKER PROMPT
# ============================================================

WORKER_SYSTEM = """
You are a professional blog writer working inside a general-purpose AI blog
writing system.

Your task is to write one section of a larger blog based strictly on the
section plan and the information provided to you.

IMPORTANT AUDIENCE RULE:
- Assume the reader is general audience.
- Write for the audience naturally implied by the topic.
- Match the complexity and terminology to the subject.
- Technical terminology is appropriate when the topic requires it.
- Avoid technical or developer terminology when it is irrelevant to the topic.

IMPORTANT STYLE RULE:
Write naturally and clearly.

Prioritize:
- Accuracy
- Clarity
- Relevance
- Reader usefulness
- Logical explanation
- Appropriate depth
- Natural transitions
- Concrete examples when useful

Avoid:
- Unnecessary jargon
- Forced technical language
- Forced programming analogies
- Developer-centric metaphors
- Repetitive explanations
- Generic filler
- Claims that sound authoritative but are unsupported by the provided
  evidence

CODE RULE:
Only include code when the section plan explicitly indicates that code is
required AND code is genuinely relevant to the topic.

Never add code simply because this system is capable of generating code.

For non-technical topics, do not introduce programming examples, software
concepts, debugging terminology, developer metaphors, or engineering
terminology unless they are directly relevant to the subject.

RESEARCH AND ACCURACY:
- Use the provided evidence when it is relevant to the section.
- Do not invent statistics, measurements, studies, technical claims, or other
  factual details.
- Do not exaggerate conclusions from the available evidence.
- If evidence is insufficient for a specific claim, avoid presenting the claim
  as established fact.
- Prefer simple and accurate explanations over unnecessarily sophisticated
  explanations.

SECTION RULE:
Write only the requested section.

Do not write the entire blog.
Do not add an unrelated introduction or conclusion.
Do not repeat content that belongs to another section.

The section should fit naturally into the overall blog described by the plan.

Return only the section content in the format required by the application.
"""


# ============================================================
# 13. WORKER HELPERS
# ============================================================

def _build_worker_payload(
    plan: Plan,
    task: Task,
    topic: str,
    mode: str,
    evidence: List[EvidenceItem],
) -> dict:

    return {
        "plan": plan.model_dump(),
        "topic": topic,
        "task": task.model_dump(),
        "mode": mode,
        "evidence": [
            item.model_dump()
            for item in evidence[
                :MAX_EVIDENCE_SOURCES
            ]
        ],
    }


def _generate_worker_section(
    payload: dict,
) -> tuple[int, str]:

    task = Task(
        **payload["task"]
    )

    plan = Plan(
        **payload["plan"]
    )

    evidence = [
        EvidenceItem(**item)
        for item in payload.get(
            "evidence",
            []
        )[
            :MAX_EVIDENCE_SOURCES
        ]
    ]

    topic = payload["topic"]

    mode = payload.get(
        "mode",
        "closed_book",
    )

    bullets_text = "\n".join(
        f"- {bullet}"
        for bullet in task.bullets
    )

    evidence_lines = []

    for item in evidence:

        evidence_lines.append(
            (
                f"- Title: {item.title}\n"
                f"  URL: {item.url}\n"
                f"  Date: "
                f"{item.published_at or 'unknown'}\n"
                f"  Snippet: "
                f"{item.snippet or ''}"
            )
        )

    evidence_text = "\n".join(
        evidence_lines
    )

    response = llm.invoke(
        [
            SystemMessage(
                content=WORKER_SYSTEM
            ),
            HumanMessage(
                content=(
                    f"Blog title:\n"
                    f"{plan.blog_title}\n\n"

                    f"Audience:\n"
                    f"{plan.audience}\n\n"

                    f"Tone:\n"
                    f"{plan.tone}\n\n"

                    f"Blog kind:\n"
                    f"{plan.blog_kind}\n\n"

                    f"Constraints:\n"
                    f"{plan.constraints}\n\n"

                    f"Topic:\n"
                    f"{topic}\n\n"

                    f"Mode:\n"
                    f"{mode}\n\n"

                    f"Section title:\n"
                    f"{task.title}\n\n"

                    f"Section type:\n"
                    f"{task.section_type}\n\n"

                    f"Goal:\n"
                    f"{task.goal}\n\n"

                    f"Brief:\n"
                    f"{task.brief}\n\n"

                    f"Target words:\n"
                    f"{task.target_words}\n\n"

                    f"Tags:\n"
                    f"{task.tags}\n\n"

                    f"requires_research:\n"
                    f"{task.requires_research}\n\n"

                    f"requires_citations:\n"
                    f"{task.requires_citations}\n\n"

                    f"requires_code:\n"
                    f"{task.requires_code}\n\n"

                    f"Bullets:\n"
                    f"{bullets_text}\n\n"

                    "Evidence "
                    "(ONLY use these URLs when citing):\n"
                    f"{evidence_text}"
                )
            ),
        ]
    )

    # IMPORTANT GEMINI FIX:
    # response.content may be a list.
    section_md = _extract_response_text(
        response
    )

    if not section_md:

        raise ValueError(
            f"Worker {task.id} received an empty "
            "response from Gemini."
        )

    return (
        task.id,
        section_md,
    )


# ============================================================
# 14. SEQUENTIAL WORKERS
# ============================================================

def workers_node(
    state: ChatState,
) -> dict:
    """
    Generate all planned sections sequentially.

    The orchestrator decides whether there are 5, 6, or 7
    sections. Workers then process exactly those tasks.

    Sequential execution is intentional to avoid launching
    multiple Gemini requests concurrently and hitting
    provider-side rate limits.
    """

    plan = state.get(
        "plan"
    )

    if plan is None:

        raise ValueError(
            "Cannot run workers because plan is None."
        )

    tasks = plan.tasks

    task_count = len(tasks)

    if not (
        MIN_SECTIONS
        <= task_count
        <= MAX_SECTIONS
    ):

        raise ValueError(
            f"Expected between "
            f"{MIN_SECTIONS} and {MAX_SECTIONS} tasks, "
            f"got {task_count}"
        )

    evidence = state.get(
        "evidence",
        []
    )[
        :MAX_EVIDENCE_SOURCES
    ]

    sections = []

    for task in tasks:

        payload = _build_worker_payload(
            plan=plan,
            task=task,
            topic=state["topic"],
            mode=state.get(
                "mode",
                "closed_book",
            ),
            evidence=evidence,
        )

        task_id, section_md = (
            _generate_worker_section(
                payload
            )
        )

        sections.append(
            (
                task_id,
                section_md,
            )
        )

    return {
        "sections": sections
    }


# ============================================================
# 15. FILENAME SANITIZATION
# ============================================================

def safe_filename(title: str) -> str:

    filename = re.sub(
        r'[<>:"/\\|?*]',
        "",
        title,
    )

    filename = filename.strip()

    if not filename:

        filename = "blog"

    return filename


# ============================================================
# 16. REDUCER
# ============================================================

def reducer(
    state: ChatState,
) -> dict:
    """
    Combine all dynamically generated worker sections in
    task-ID order and return the final Markdown content.
    """

    plan = state.get(
        "plan"
    )

    if plan is None:

        raise ValueError(
            "Cannot reduce because plan is None."
        )

    sections = state.get(
        "sections",
        []
    )

    ordered_sections = [
        markdown
        for _, markdown
        in sorted(
            sections,
            key=lambda item: item[0],
        )
    ]

    body = "\n\n".join(
        ordered_sections
    ).strip()

    final_md = (
        f"# {plan.blog_title}\n\n"
        f"{body}\n"
    )

    return {
        "final_md": final_md
    }


# ============================================================
# 17. BUILD LANGGRAPH
# ============================================================

g = StateGraph(
    ChatState
)

g.add_node(
    "router",
    router_node,
)

g.add_node(
    "research",
    research_node,
)

g.add_node(
    "orchestrator",
    orchestrator_node,
)

# One node executes the five workers sequentially.
g.add_node(
    "workers",
    workers_node,
)

g.add_node(
    "reducer",
    reducer,
)


g.add_edge(
    START,
    "router",
)


g.add_conditional_edges(
    "router",
    route_next,
    {
        "research": "research",
        "orchestrator": "orchestrator",
    },
)


g.add_edge(
    "research",
    "orchestrator",
)


g.add_edge(
    "orchestrator",
    "workers",
)


g.add_edge(
    "workers",
    "reducer",
)


g.add_edge(
    "reducer",
    END,
)


app = g.compile()


# ============================================================
# 18. INITIAL STATE
# ============================================================

def _initial_state(
    topic: str,
) -> ChatState:

    return {
        "topic": topic,

        "mode": "",

        "needs_research": False,

        "queries": [],

        "evidence": [],

        "plan": None,

        "sections": [],

        "final_md": "",
    }


# ============================================================
# 19. NORMAL RUNNER
# ============================================================

def run(topic: str):

    topic = str(
        topic
    ).strip()

    if not topic:

        raise ValueError(
            "Topic cannot be empty."
        )

    return app.invoke(
        _initial_state(topic)
    )


# ============================================================
# 20. STREAMING RUNNER
# ============================================================

def run_stream(topic: str):
    """
    The worker LLM calls are intentionally sequential
    inside the workers node. The number of calls is determined
    by the orchestrator's 5–7 section plan.
    """

    topic = str(
        topic
    ).strip()

    if not topic:

        raise ValueError(
            "Topic cannot be empty."
        )

    initial_state = _initial_state(
        topic
    )

    for event in app.stream(
        initial_state,
        stream_mode="updates",
    ):
        yield event


# ============================================================
# 21. CONVENIENCE FUNCTION
# ============================================================

def generate_blog(
    topic: str,
) -> str:

    result = run(topic)

    return result["final_md"]


# ============================================================
# 22. MAIN
# ============================================================

if __name__ == "__main__":

    topic = input(
        "Enter your blog topic: "
    ).strip()

    if not topic:

        print(
            "Please enter a valid blog topic."
        )

    else:

        print(
            "\nGenerating blog...\n"
        )

        result = run(topic)

        print(
            result["final_md"]
        )
