from typing import TypedDict, List, Annotated, Literal, Optional
import operator
import re
from urllib.parse import urlparse

from dotenv import load_dotenv
from pydantic import BaseModel, Field, ValidationError

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.messages import SystemMessage, HumanMessage
from langchain_community.tools.tavily_search import TavilySearchResults

from langgraph.graph import StateGraph, START, END
from langgraph.types import Send


# ============================================================
# 1. ENVIRONMENT
# ============================================================

load_dotenv()


# ============================================================
# 2. CONFIGURATION
# ============================================================

MODEL_NAME = "gemini-3.1-flash-lite"

# IMPORTANT:
# Only this many useful sources are sent to the evidence
# synthesizer and later writing stages.
MAX_EVIDENCE_SOURCES = 8

# Research breadth. We can collect more than 8 raw results,
# rank them locally, and only send the best 8 to Gemini.
MAX_RESEARCH_QUERIES = 10
TAVILY_RESULTS_PER_QUERY = 4

# Keep snippets compact so prompts do not become unnecessarily
# large.
MAX_SNIPPET_CHARS = 900

# The worker graph uses LangGraph fan-out so the independent
# section-generation calls can run concurrently. The planner
# is capped at 5–7 sections, which stays below the user's
# stated 15 RPM Gemini request limit for one generation batch.
MIN_SECTIONS = 5
MAX_SECTIONS = 7


# ============================================================
# 3. LLM
# ============================================================

llm = ChatGoogleGenerativeAI(
    model=MODEL_NAME,
    temperature=0.7,
)


# ============================================================
# 4. PYDANTIC SCHEMAS
# ============================================================

class Task(BaseModel):
    """
    Represents one section/task of the blog.
    """

    id: int

    title: str

    goal: str = Field(
    ...,
    description=(
        "The single primary purpose of this section. "
        "It must be clearly distinct from the purpose of every other section."
    ),
    )

    bullets: List[str] = Field(
    ...,
    description=(
        "3–6 concrete pieces of information that are exclusively "
        "owned by this section. These should not duplicate facts, "
        "concepts, explanations, examples, or responsibilities "
        "assigned to another section."
    ),
    )

    target_words: int = Field(
        ...,
        description="Target word count for this section.",
    )

    section_type: Literal[
        "intro",
        "core",
        "examples",
        "checklist",
        "common_mistakes",
        "conclusion",
    ] = Field(
        ...,
        description="Type of the blog section.",
    )

    brief: str = Field(
    ...,
    description=(
        "A concise description of exactly what this section should "
        "explain. It must stay within this section's ownership boundary "
        "and must not develop topics assigned to other sections."
    ),
    )

    tags: List[str] = Field(
        default_factory=list,
        description="Important tags/topics for this section.",
    )

    requires_research: bool = Field(
        default=False,
        description="Whether this section requires fresh research.",
    )

    requires_citations: bool = Field(
        default=False,
        description="Whether outside-world claims need citations.",
    )

    requires_code: bool = Field(
        default=False,
        description="Whether this section must contain a code example.",
    )

    must_not_cover: List[str] = Field(
        default_factory=list,
        description=(
        "Topics, facts, concepts, examples, or content areas "
        "that belong to other sections and must not be developed "
        "in this section."
    ),
)


class Plan(BaseModel):
    """
    Complete blog plan generated by the orchestrator.
    """

    blog_title: str

    audience: str = Field(
        description="Who this blog is made for.",
    )

    tone: str = Field(
        description=(
            "Writing tone, for example practical, crisp, "
            "technical, beginner-friendly, etc."
        ),
    )

    blog_kind: Literal[
        "tutorial",
        "news_roundup",
    ] = Field(
        default="tutorial",
        description="The overall type of the blog.",
    )

    constraints: List[str] = Field(
        default_factory=list,
        description="Important constraints that apply to the blog.",
    )

    tasks: List[Task] = Field(
    ...,
    min_length=MIN_SECTIONS,
    max_length=MAX_SECTIONS,
    description=(
        "Dynamically chosen blog sections/tasks. "
        "Must contain between 5 and 7 sections."
    ),
    )


class RouterDecision(BaseModel):
    """
    Decision produced by the routing node.
    """

    needs_research: bool

    mode: Literal[
        "closed_book",
        "hybrid",
        "open_book",
    ]

    queries: List[str] = Field(
        default_factory=list,
        max_length=10,
    )


class EvidenceItem(BaseModel):
    """
    One research source.
    """

    title: str

    url: str

    published_at: Optional[str] = None

    snippet: Optional[str] = None

    source: Optional[str] = None


class EvidencePack(BaseModel):
    """
    Collection of research sources.
    """

    evidence: List[EvidenceItem] = Field(
        default_factory=list,
        max_length=MAX_EVIDENCE_SOURCES,
    )


# ============================================================
# 5. LANGGRAPH STATE
# ============================================================

class ChatState(TypedDict):
    """
    Shared state used by the LangGraph workflow.
    """

    topic: str

    mode: str

    needs_research: bool

    queries: List[str]

    evidence: List[EvidenceItem]

    plan: Optional[Plan]

    sections: Annotated[
        List[tuple[int, str]],
        operator.add,
    ]

    final_md: str


# ============================================================
# 6. GEMINI RESPONSE HELPERS
# ============================================================

def _extract_response_text(response) -> str:
    """
    Normalize LangChain/Gemini response content into plain text.

    Gemini may expose response.content as:
    - a string
    - a list of content blocks
    - a list of strings
    - a list of dictionaries containing text
    - nested content structures
    """

    content = getattr(response, "content", response)

    if isinstance(content, str):
        return content.strip()

    if isinstance(content, list):

        parts: List[str] = []

        def collect(item) -> None:

            if isinstance(item, str):
                if item.strip():
                    parts.append(item)
                return

            if isinstance(item, dict):

                text_value = item.get("text")

                if isinstance(text_value, str):
                    if text_value.strip():
                        parts.append(text_value)
                    return

                nested = item.get("content")

                if isinstance(nested, str):
                    if nested.strip():
                        parts.append(nested)
                    return

                if isinstance(nested, list):
                    for nested_item in nested:
                        collect(nested_item)

                return

        for item in content:
            collect(item)

        return "\n".join(parts).strip()

    return str(content).strip()


def _invoke_structured(schema, messages):
    """
    Invoke Gemini using LangChain structured output.

    Gemini's structured-output path returns a Pydantic object.
    This helper also provides a useful error if the provider
    returns something unexpected.
    """

    structured_llm = llm.with_structured_output(
        schema
    )

    result = structured_llm.invoke(messages)

    if isinstance(result, schema):
        return result

    try:
        return schema.model_validate(result)
    except Exception as exc:
        raise ValueError(
            f"Gemini returned an unexpected structured-output "
            f"format for {schema.__name__}: {result!r}"
        ) from exc


# ============================================================
# 7. ROUTER
# ============================================================

ROUTER_SYSTEM = """
You are a routing module for a general-purpose blog writing agent.

Your job is to analyze the user's requested topic and decide whether the blog
requires external web research.

The blog may cover ANY subject, including but not limited to:
- Technology
- Programming
- Science
- Health and fitness
- Sports
- Education
- History
- Travel
- Business
- Lifestyle
- Hobbies
- General knowledge

Choose "web" when:
- The topic depends on current or changing information.
- The user asks about recent events, current trends, latest information,
  current statistics, recent products, or other time-sensitive facts.
- External evidence would materially improve factual accuracy.
- The topic contains claims that should be supported by recent or authoritative
  sources.

Choose "closed_book" when:
- The topic can be explained accurately without current web information.
- The topic is primarily evergreen knowledge, concepts, explanations,
  educational material, opinions, or general guidance.
- External research is not necessary for producing a useful and accurate blog.

Return ONLY valid JSON matching the required RouterDecision schema.
Do not include markdown, explanations, or additional text.
"""


def router_node(state: ChatState) -> dict:

    topic = state["topic"]

    decision = _invoke_structured(
        RouterDecision,
        [
            SystemMessage(
                content=ROUTER_SYSTEM
            ),
            HumanMessage(
                content=(
                    "User's blog topic:\n"
                    f"{topic}"
                )
            ),
        ],
    )

    queries = [
        q.strip()
        for q in decision.queries
        if isinstance(q, str) and q.strip()
    ][:MAX_RESEARCH_QUERIES]

    return {
        "needs_research": decision.needs_research,
        "mode": decision.mode,
        "queries": queries,
    }


def route_next(state: ChatState) -> str:

    if state["needs_research"]:
        return "research"

    return "orchestrator"


# ============================================================
# 8. TAVILY SEARCH
# ============================================================

def _compact_snippet(value: Optional[str]) -> str:

    if not value:
        return ""

    text = " ".join(
        str(value).split()
    )

    return text[:MAX_SNIPPET_CHARS]


def _domain_from_url(url: str) -> str:

    try:
        return (
            urlparse(url)
            .netloc
            .lower()
            .replace("www.", "")
        )
    except Exception:
        return ""


def _tavily_search(
    query: str,
    max_results: int = TAVILY_RESULTS_PER_QUERY,
) -> List[dict]:
    """
    Run one Tavily search and normalize the output.
    """

    tool = TavilySearchResults(
        max_results=max_results
    )

    results = tool.invoke(
        {
            "query": query
        }
    )

    normalized: List[dict] = []

    for result in results or []:

        if not isinstance(result, dict):
            continue

        url = str(
            result.get("url")
            or ""
        ).strip()

        if not url:
            continue

        normalized.append(
            {
                "title": str(
                    result.get("title")
                    or ""
                ).strip(),

                "url": url,

                "snippet": _compact_snippet(
                    result.get("content")
                    or result.get("snippet")
                    or ""
                ),

                "published_at": (
                    result.get("published_date")
                    or result.get("published_at")
                ),

                "source": (
                    result.get("source")
                    or _domain_from_url(url)
                ),
            }
        )

    return normalized



# ============================================================
# 9. DETERMINISTIC SOURCE RANKING
# ============================================================

def _domain_matches(
    domain: str,
    allowed_domain: str,
) -> bool:
    """
    Return True only when the domain is exactly the allowed
    domain or is a legitimate subdomain of it.

    Examples:

    github.com            -> True
    docs.github.com       -> True
    notgithub.com         -> False
    github.com.evil.com   -> False
    """

    domain = domain.lower().strip(".")
    allowed_domain = (
        allowed_domain
        .lower()
        .strip(".")
    )

    return (
        domain == allowed_domain
        or domain.endswith(
            "." + allowed_domain
        )
    )


def _source_authority_score(item: dict) -> int:
    """
    Lightweight deterministic authority scoring.

    This happens BEFORE the evidence synthesizer, so only the
    best ~10–15 sources ever reach the LLM.
    """

    url = item.get(
        "url",
        "",
    )

    domain = _domain_from_url(
        url
    )

    score = 0

    high_authority_domains = (
        ".gov",
        ".edu",
        "github.com",
        "arxiv.org",
        "openai.com",
        "developers.google.com",
        "ai.google.dev",
        "cloud.google.com",
        "python.org",
        "pytorch.org",
        "tensorflow.org",
        "microsoft.com",
        "aws.amazon.com",
        "anthropic.com",
        "meta.com",
        "developer.mozilla.org",
    )

    reputable_domains = (
        "reuters.com",
        "apnews.com",
        "bbc.com",
        "nytimes.com",
        "techcrunch.com",
        "theverge.com",
        "wired.com",
        "nature.com",
        "arstechnica.com",
    )

    # --------------------------------------------------------
    # High-authority sources
    # --------------------------------------------------------

    if any(
        (
            domain.endswith(suffix)
            if suffix.startswith(".")
            else _domain_matches(
                domain,
                suffix,
            )
        )
        for suffix in high_authority_domains
    ):
        score += 8

    # --------------------------------------------------------
    # Reputable sources
    # --------------------------------------------------------

    if any(
        _domain_matches(
            domain,
            suffix,
        )
        for suffix in reputable_domains
    ):
        score += 5

    # --------------------------------------------------------
    # Freshness
    # --------------------------------------------------------

    if item.get(
        "published_at"
    ):
        score += 1

    # --------------------------------------------------------
    # Useful snippet
    # --------------------------------------------------------

    if item.get(
        "snippet"
    ):
        score += 2

    return score

def _rank_and_select_sources(
    raw_results: List[dict],
    topic: str,
    queries: List[str],
) -> List[dict]:
    """
    Deduplicate, score and select at most 8 sources.

    The full raw Tavily result set is NEVER passed to Gemini.
    """

    query_terms = set(
        re.findall(
            r"\b[a-zA-Z0-9][a-zA-Z0-9_-]{2,}\b",
            " ".join(
                [topic] + queries
            ).lower(),
        )
    )

    unique = {}

    for item in raw_results:

        url = item.get("url", "").strip()

        if not url:
            continue

        if url not in unique:
            unique[url] = item
            continue

        # Keep the richer duplicate.
        old = unique[url]

        if len(
            item.get("snippet", "")
        ) > len(
            old.get("snippet", "")
        ):
            unique[url] = item

    scored = []

    for item in unique.values():

        title = item.get(
            "title",
            "",
        ).lower()

        snippet = item.get(
            "snippet",
            "",
        ).lower()

        text = f"{title} {snippet}"

        overlap = sum(
            1
            for term in query_terms
            if term in text
        )

        score = (
            overlap * 2
            + _source_authority_score(item)
        )

        scored.append(
            (
                score,
                item,
            )
        )

    scored.sort(
        key=lambda pair: (
            pair[0],
            len(
                pair[1].get(
                    "snippet",
                    "",
                )
            ),
        ),
        reverse=True,
    )

    return [
        item
        for _, item in scored[
            :MAX_EVIDENCE_SOURCES
        ]
    ]


# ============================================================
# 10. RESEARCH
# ============================================================

RESEARCH_SYSTEM = """
You are a research synthesizer for technical writing.

You are given ONLY the most useful web sources selected by a
deterministic ranking stage.

Create an EvidencePack from those sources.

Rules:

- Preserve the supplied URLs exactly.
- Only include items with a non-empty URL.
- Do not invent URLs.
- Prefer relevant and authoritative sources.
- Prefer official documentation, company sources,
  research papers, government sources, and reputable
  publications when available.
- Preserve an explicitly supplied publication date.
- Never guess a publication date.
- Keep snippets concise.
- Do not create additional sources.
- Deduplicate by URL.
- Return at most 8 evidence items.

Return only the EvidencePack fields.
"""


def research_node(state: ChatState) -> dict:
    """
    Search Tavily, rank locally, and send ONLY the best 8
    sources to Gemini.
    """

    queries = (
        state.get(
            "queries",
            [],
        )
        or []
    )[:MAX_RESEARCH_QUERIES]

    raw_results: List[dict] = []

    for query in queries:

        try:

            results = _tavily_search(
                query,
                max_results=TAVILY_RESULTS_PER_QUERY,
            )

            raw_results.extend(results)

        except Exception as exc:

            print(
                f"Research failed for query "
                f"'{query}': {exc}"
            )

    if not raw_results:

        return {
            "evidence": []
        }

    selected_sources = _rank_and_select_sources(
        raw_results=raw_results,
        topic=state["topic"],
        queries=queries,
    )

    # IMPORTANT:
    # Only selected_sources (max 8) are passed to Gemini.
    compact_sources = []

    for item in selected_sources:

        compact_sources.append(
            {
                "title": item.get(
                    "title",
                    "",
                ),

                "url": item.get(
                    "url",
                    "",
                ),

                "snippet": item.get(
                    "snippet",
                    "",
                ),

                "published_at": item.get(
                    "published_at"
                ),

                "source": item.get(
                    "source"
                ),
            }
        )

    pack = _invoke_structured(
        EvidencePack,
        [
            SystemMessage(
                content=RESEARCH_SYSTEM
            ),
            HumanMessage(
                content=(
                    "Topic:\n"
                    f"{state['topic']}\n\n"
                    "Selected source candidates "
                    f"(maximum {MAX_EVIDENCE_SOURCES}):\n"
                    f"{compact_sources}"
                )
            ),
        ],
    )

    # Final deterministic URL deduplication + hard cap.
    dedup = {}

    for item in pack.evidence:

        if item.url:

            dedup[
                item.url
            ] = item

    final_evidence = list(
        dedup.values()
    )[
        :MAX_EVIDENCE_SOURCES
    ]

    return {
        "evidence": final_evidence
    }


# ============================================================
# 11. ORCHESTRATOR
# ============================================================
ORCH_MESSAGE = """
You are the senior content strategist and blog planner for a general-purpose
AI blog writing system.

Your job is to create a strong, logical, reader-focused plan for the user's
requested topic.

The blog can be about ANY subject.

IMPORTANT AUDIENCE RULE:
- Assume the reader is a general audience.
- Determine the appropriate level of explanation from the topic itself.
- Use technical terminology only when it is relevant to the topic.
- If the topic is technical, technical terminology is appropriate.
- If the topic is non-technical, use language appropriate for a general reader.
- Never inject programming, software engineering, developer terminology, or
  technical analogies unless they are genuinely relevant to the topic.


============================================================
SECTION STRUCTURE
============================================================

Create between 5 and 7 meaningful sections.

The exact structure must be determined by the topic.

Do NOT use a fixed template for every blog.

Choose sections that naturally explain the specific topic and provide a
logical progression for the reader.


============================================================
SECTION OWNERSHIP — CRITICAL
============================================================

The blog will be written by multiple independent workers running concurrently.

Each worker will receive exactly ONE section.

Therefore, sections MUST have strict and exclusive information ownership.

Every important fact, concept, statistic, historical event, example, process,
argument, explanation, or topic MUST have ONE clear section owner.

NEVER assign the same major information to multiple sections.

For every section:

1. Define exactly what information the section owns.
2. Define the specific concepts, facts, examples, or ideas that belong in it.
3. Use the `bullets` field to list concrete information that this section owns.
4. Use the `must_not_cover` field to explicitly identify important topics that
   belong to OTHER sections.
5. Make sure the section's bullets and `must_not_cover` do not contradict each
   other.

The `must_not_cover` field is a HARD boundary for the worker.

If a topic belongs to another section, explicitly place that topic in
`must_not_cover`.

Do not leave important boundaries implicit when they can be stated clearly.


============================================================
HOW TO AVOID OVERLAPPING SECTIONS
============================================================

Before creating the final plan, mentally perform an ownership check.

For every major topic ask:

"Which ONE section owns this information?"

Assign it to exactly one section.

Then ask:

"Could another section accidentally explain this same information?"

If yes, add that topic to the other section's `must_not_cover`.

Sections should complement one another, not compete with one another.


============================================================
SECTION EXAMPLES
============================================================

For example, if the topic is about the G20, a possible ownership structure
could be:

Section: Origins and Evolution

Owns:
- Why the G20 was created
- The 1999 establishment
- Its evolution from a finance-focused forum
- Major historical changes in its role

Must NOT cover:
- Current membership details
- Current organizational structure
- Detailed discussion of recent summit initiatives


Section: Membership and Structure

Owns:
- Current membership
- Member categories
- Rotating presidency
- How the forum operates

Must NOT cover:
- Detailed history of the G20's creation
- Detailed analysis of individual summit initiatives


Section: Current Role and Influence

Owns:
- What the G20 does today
- Areas currently addressed by the forum
- Its influence on international cooperation

Must NOT cover:
- Detailed history of its creation
- Detailed membership mechanics
- Repeating the full historical evolution


These are ONLY examples of ownership thinking.

Do not force this exact structure onto unrelated topics.


============================================================
INTRODUCTION RULE
============================================================

If an introduction section is appropriate:

- Introduce the topic.
- Establish why the topic matters.
- Give only enough context for the reader to understand the article.
- Do NOT provide detailed explanations that belong to later sections.
- Do NOT repeat statistics, examples, history, or detailed concepts that later
  sections own.

The introduction should set up the article, not consume the article.


============================================================
CONCLUSION RULE
============================================================

If a conclusion section is appropriate:

- Synthesize the main ideas.
- Explain the overall takeaway.
- Leave the reader with a useful final perspective.

Do NOT:

- Re-explain every section.
- Repeat large amounts of information.
- Introduce substantial new concepts.
- Repeat detailed statistics or examples from the body.


============================================================
BULLET RULE
============================================================

Every bullet must describe information primarily owned by that section.

Bullets must be:

- Concrete
- Topic-specific
- Non-overlapping
- Useful to the worker writing that section

Avoid vague bullets such as:

- "Explain the topic"
- "Discuss its importance"
- "Talk about key points"
- "Explain how it works"

Instead, identify exactly WHAT the worker should explain.


============================================================
MUST_NOT_COVER RULE
============================================================

`must_not_cover` should contain the important topics that belong to other
sections.

Examples:

- Current membership
- Historical origins
- Detailed implementation steps
- Advanced technical architecture
- Specific examples assigned to another section
- Detailed statistics owned by another section

Do NOT simply copy the same section's bullets into `must_not_cover`.

The purpose of `must_not_cover` is to protect boundaries between workers.


============================================================
WRITING QUALITY
============================================================

The goal is to create a useful, accurate, engaging, and logically structured
blog — not to make the content sound unnecessarily sophisticated.

Prefer:

- Clear explanations
- Useful information
- Logical progression
- Appropriate depth
- Concrete examples when useful
- Reader-friendly language
- Topic-specific terminology when relevant

Avoid:

- Unnecessary jargon
- Forced technical terminology
- Forced analogies
- Developer-oriented language for non-technical topics
- Overly complicated explanations
- Generic filler
- Repetitive sections
- Generic sections that could apply to any unrelated topic


============================================================
CODE RULE
============================================================

Code is OPTIONAL.

Include code only when it is genuinely useful and relevant to the topic.

For programming, software, technical, or other code-related topics:

- Code may be appropriate.
- Set `requires_code` to true only when a code example genuinely improves
  the section.

For non-technical topics:

- Set `requires_code` to false.
- Do not force programming examples into the article.


============================================================
RESEARCH RULE
============================================================

When research evidence is provided:

- Use the evidence to guide factual coverage.
- Prioritize authoritative and relevant sources.
- Do not invent facts that are not supported by the evidence.
- Do not force every source into every section.
- Assign each important research fact to the section that owns it.
- Avoid repeating the same researched fact across multiple sections.
- Mark `requires_research` and `requires_citations` according to the actual
  needs of the section.


============================================================
FINAL OWNERSHIP CHECK
============================================================

Before returning the plan, verify ALL of the following:

1. There are 5–7 sections.
2. Every section has a distinct purpose.
3. Every section has concrete, topic-specific bullets.
4. Major information has exactly one clear owner.
5. Important cross-section boundaries are represented in `must_not_cover`.
6. No section substantially duplicates another section.
7. The introduction does not consume detailed body content.
8. The conclusion does not repeat the entire article.
9. Code is not forced into non-technical topics.
10. Research is used only where relevant.
11. The sections together form a logical progression.
12. The plan can safely be handed to independent parallel workers without
    causing them to write overlapping content.


============================================================
INPUT
============================================================

Topic:
{topic}

Research mode:
{research_mode}

Evidence:
{evidence}


Return the result using the required Plan schema.
"""
def validate_plan(plan: Plan) -> Plan:
    """
    Validate the orchestrator's dynamic blog plan.

    The orchestrator may choose 5, 6, or 7 sections,
    but never fewer than 5 or more than 7.
    """

    task_count = len(plan.tasks)

    if not (
        MIN_SECTIONS
        <= task_count
        <= MAX_SECTIONS
    ):

        raise ValueError(
            f"Plan must contain between "
            f"{MIN_SECTIONS} and {MAX_SECTIONS} sections, "
            f"got {task_count}"
        )

    task_ids = [
        task.id
        for task in plan.tasks
    ]

    if len(set(task_ids)) != len(task_ids):

        raise ValueError(
            "Task IDs must be unique."
        )

    expected_ids = list(
        range(
            1,
            task_count + 1,
        )
    )

    if sorted(task_ids) != expected_ids:

        raise ValueError(
            "Task IDs must be sequential starting from 1. "
            f"Expected {expected_ids}, got {sorted(task_ids)}"
        )

    # common_mistakes_count = sum(
    #     task.section_type
    #     == "common_mistakes"
    #     for task in plan.tasks
    # )

    # if common_mistakes_count != 1:

    #     raise ValueError(
    #         "Plan must contain exactly one "
    #         "'common_mistakes' section."
        # )

    return plan


def orchestrator_node(
    state: ChatState,
) -> dict:

    evidence = state.get(
        "evidence",
        []
    )

    # Never pass more than the selected 8 sources.
    evidence_for_prompt = [
        item.model_dump()
        for item in evidence[
            :MAX_EVIDENCE_SOURCES
        ]
    ]

    mode = state.get(
        "mode",
        "closed_book",
    )

    plan = _invoke_structured(
        Plan,
        [
            SystemMessage(
                content=ORCH_MESSAGE
            ),
            HumanMessage(
                content=(
                    f"Topic:\n"
                    f"{state['topic']}\n\n"

                    f"Mode:\n"
                    f"{mode}\n\n"

                    "Evidence "
                    "(ONLY use for fresh claims; "
                    "may be empty):\n"
                    f"{evidence_for_prompt}"
                )
            ),
        ],
    )

    plan = validate_plan(plan)

    return {
        "plan": plan
    }


# ============================================================
# 12. WORKER PROMPT
# ============================================================
WORKER_SYSTEM = """
You are a specialist writer in a parallel multi-agent blog writing system.

You are responsible for EXACTLY ONE section of a larger blog.

Other workers are independently writing the other sections concurrently.
You must therefore respect strict section ownership.

==================================================
1. YOUR RESPONSIBILITY
==================================================

Write ONLY your assigned section.

Your assigned section is defined by:
- Its title
- Its goal
- Its bullets
- Its brief
- Its section type
- Its must_not_cover boundaries

Treat these instructions as the boundaries of your work.

Do NOT write the entire blog.

Do NOT write another worker's section.

Do NOT expand your section into topics that belong to another section.


==================================================
2. SECTION OWNERSHIP — CRITICAL
==================================================

Each section has an exclusive information responsibility.

You MUST:

- Cover the important points listed in your section's bullets.
- Stay focused on the goal of your section.
- Respect the topics listed in must_not_cover.
- Assume that another worker owns every other section.
- Avoid developing another section's main ideas.
- Avoid repeating facts, statistics, definitions, examples, historical
  events, explanations, or arguments that belong primarily to another
  section.

If another section's topic is necessary for context:

- Mention it briefly only when necessary.
- Do not explain it in detail.
- Do not turn that brief reference into a second section.

The purpose of your section is to ADD new information to the article,
not repeat information that another worker is already responsible for.


==================================================
3. MUST_NOT_COVER — CRITICAL
==================================================

The section plan may provide a list called must_not_cover.

These are topics or information areas owned by other sections.

You MUST NOT develop these topics.

For example, if your section is:

"Membership and Structure"

and must_not_cover contains:

- Origins of the G20
- Asian financial crisis
- Historical evolution
- Recent summit outcomes

then you may briefly mention the origins if needed for context, but you
must NOT explain the Asian financial crisis or the history of the G20.

Treat must_not_cover as a hard boundary.


==================================================
4. OTHER SECTION OWNERSHIP
==================================================

You may be shown the complete section map.

Use it to understand what other workers are responsible for.

If another section owns a topic, do not develop that topic in your section.

Do NOT attempt to make your section self-contained by explaining every
important aspect of the overall topic.

The complete blog will be assembled later by a reducer.

Your job is only to produce your assigned contribution.


==================================================
5. AUDIENCE
==================================================

Assume a general audience unless the topic clearly requires a different
level of expertise.

Write for the audience naturally implied by the topic.

Match terminology and depth to the subject.

For technical topics:
- Technical terminology is appropriate when relevant.
- Explain specialized concepts clearly when the reader needs the context.

For non-technical topics:
- Use natural, accessible language.
- Do not introduce programming, software engineering, developer terminology,
  or technical metaphors unless directly relevant to the subject.


==================================================
6. WRITING STYLE
==================================================

Write naturally, clearly, and professionally.

Prioritize:

- Accuracy
- Clarity
- Relevance
- Reader usefulness
- Logical explanation
- Appropriate depth
- Natural transitions
- Concrete examples when genuinely useful

Avoid:

- Unnecessary jargon
- Forced technical language
- Forced programming analogies
- Developer-centric metaphors
- Generic filler
- Repetitive explanations
- Rephrasing the same point multiple times
- Artificially sophisticated language
- Unsupported authoritative-sounding claims


==================================================
7. INTRODUCTION SECTIONS
==================================================

If your assigned section is the introduction:

- Briefly establish what the topic is.
- Explain why the topic matters.
- Give the reader enough context to understand the rest of the article.
- Do NOT explain the detailed content owned by later sections.
- Do NOT provide a detailed history, feature list, process explanation,
  examples, or current developments unless those are explicitly owned
  by the introduction.

The introduction should orient the reader, not write the entire article.


==================================================
8. CONCLUSION SECTIONS
==================================================

If your assigned section is the conclusion:

- Synthesize the major ideas of the article.
- Give the reader a useful final takeaway.
- Connect the major ideas at a high level.
- Do NOT repeat every section in detail.
- Do NOT introduce substantial new information.
- Do NOT simply copy or rephrase the article's earlier paragraphs.

The conclusion should provide synthesis rather than repetition.


==================================================
9. RESEARCH AND ACCURACY
==================================================

Use the provided evidence when it is relevant to your assigned section.

You do NOT need to use every provided source.

Only use evidence that supports the content you are writing.

Rules:

- Do not invent statistics.
- Do not invent dates.
- Do not invent studies.
- Do not invent quotations.
- Do not invent technical claims.
- Do not exaggerate conclusions from the evidence.
- Do not present unsupported claims as established facts.
- Prefer accurate and appropriately qualified statements.
- Do not repeat a factual claim merely because it appears in multiple
  sources.

If the available evidence does not adequately support a specific factual
claim, avoid presenting that claim as established fact.


==================================================
10. CITATIONS
==================================================

When citations are required by the section plan:

- Cite claims using only the provided evidence.
- Use the source URL exactly as provided by the application.
- Do not invent URLs.
- Do not cite a source that does not support the claim.
- Do not add a separate Sources section.
- Do not create a bibliography.

The reducer/application will handle final blog assembly.


==================================================
11. CODE
==================================================

Code is OPTIONAL.

Only include code when:

1. The section plan explicitly indicates that code is required, AND
2. Code is genuinely relevant and useful to the reader.

Never include code merely because this system can generate code.

For non-technical topics:

- Do NOT introduce programming examples.
- Do NOT introduce software concepts.
- Do NOT introduce debugging terminology.
- Do NOT introduce developer metaphors.

For technical topics:

- Include code only when it materially improves the explanation.


==================================================
12. SECTION LENGTH AND DEPTH
==================================================

Respect the target word count provided by the section plan.

Do not artificially inflate the section.

Do not add filler to reach the target.

Prioritize useful information over length.

If the section can be explained clearly in fewer words, prefer concise,
information-dense writing over repetition.


==================================================
13. HEADING RULE
==================================================

Return ONLY the body content of the assigned section.

Do NOT create the section heading yourself.

Do NOT add:

- A "# Title"
- A "## Section Title"
- "Sources"
- "References"
- A conclusion unless the assigned section is the conclusion
- An introduction unless the assigned section is the introduction
- Any content belonging to another section


==================================================
14. FINAL SELF-CHECK
==================================================

Before returning the section, check:

1. Am I writing ONLY my assigned section?
2. Did I cover the important bullets?
3. Did I follow the section goal and brief?
4. Did I avoid everything listed in must_not_cover?
5. Did I avoid developing another section's main ideas?
6. Did I avoid repeating major facts unnecessarily?
7. Did I use evidence only where relevant?
8. Did I avoid unsupported claims?
9. Did I avoid unnecessary filler?
10. Did I avoid adding my own heading?
11. Did I follow the requested word count?
12. Does this section add NEW information to the overall article?

If any answer is "no", revise the section before returning it.

Return ONLY the section content in the format required by the application.
"""


# ============================================================
# 13. WORKER HELPERS
# ============================================================

def _build_worker_payload(
    plan: Plan,
    task: Task,
    topic: str,
    mode: str,
    evidence: List[EvidenceItem],
) -> dict:

    return {
        "plan": plan.model_dump(),
        "topic": topic,
        "task": task.model_dump(),
        "mode": mode,
        "evidence": [
            item.model_dump()
            for item in evidence[
                :MAX_EVIDENCE_SOURCES
            ]
        ],
    }

def _clean_worker_section(
    section_md: str,
    task: Task,
) -> str:
    """
    Clean and normalize a worker-generated section.

    Workers are instructed to return only section body content,
    but this function protects the final blog from accidental:

    - Markdown section headings
    - Duplicate section headings
    - Streamlit [svg](...) anchor artifacts
    - Sources / References blocks
    - Excessive blank lines
    """

    if not section_md:
        return ""

    text = section_md.strip()

    # --------------------------------------------------------
    # 1. Remove Streamlit/browser anchor artifacts
    # --------------------------------------------------------
    #
    # Example unwanted output:
    #
    # [svg](http://localhost:8501/#some-heading)
    #
    text = re.sub(
        r"\[svg\]\([^)]*\)",
        "",
        text,
        flags=re.IGNORECASE,
    )

    # --------------------------------------------------------
    # 2. Remove accidental heading matching this section title
    # --------------------------------------------------------

    expected_title = re.sub(
        r"[^a-z0-9]+",
        " ",
        task.title.lower(),
    ).strip()

    lines = text.splitlines()

    while lines:

        first_line = lines[0].strip()

        heading_match = re.match(
            r"^#{1,6}\s+(.+?)\s*$",
            first_line,
        )

        if not heading_match:
            break

        actual_heading = re.sub(
            r"[^a-z0-9]+",
            " ",
            heading_match.group(1).lower(),
        ).strip()

        if actual_heading == expected_title:
            lines.pop(0)
            continue

        break

    text = "\n".join(lines).strip()

    # --------------------------------------------------------
    # 3. Remove accidental Sources / References section
    # --------------------------------------------------------
    #
    # Workers are not supposed to create their own Sources section.
    #
    # Remove everything starting from a standalone:
    #
    # ## Sources
    # ### Sources
    # Sources:
    # ## References
    # ### References
    #

    text = re.sub(
        r"\n#{1,6}\s*(?:Sources|References)\s*:?\s*\n.*$",
        "",
        text,
        flags=re.IGNORECASE | re.DOTALL,
    )

    text = re.sub(
        r"\n(?:Sources|References)\s*:?\s*\n.*$",
        "",
        text,
        flags=re.IGNORECASE | re.DOTALL,
    )

    # --------------------------------------------------------
    # 4. Remove trailing standalone Sources / References
    # --------------------------------------------------------

    text = re.sub(
        r"(?:^|\n)\s*#{1,6}\s*(?:Sources|References)\s*:?\s*$",
        "",
        text,
        flags=re.IGNORECASE,
    ).strip()

    # --------------------------------------------------------
    # 5. Remove excessive blank lines
    # --------------------------------------------------------

    text = re.sub(
        r"\n{3,}",
        "\n\n",
        text,
    ).strip()

    return text

def _generate_worker_section(
    payload: dict,
) -> tuple[int, str]:

    task = Task(
        **payload["task"]
    )

    plan = Plan(
        **payload["plan"]
    )

    evidence = [
        EvidenceItem(**item)
        for item in payload.get(
            "evidence",
            []
        )[
            :MAX_EVIDENCE_SOURCES
        ]
    ]

    topic = payload["topic"]

    mode = payload.get(
        "mode",
        "closed_book",
    )

    bullets_text = "\n".join(
        f"- {bullet}"
        for bullet in task.bullets
    )

    must_not_cover_text = "\n".join(
        f"- {item}"
        for item in task.must_not_cover
    )

    if not must_not_cover_text:
        must_not_cover_text = "- None explicitly assigned."

    evidence_lines = []

    for item in evidence:

        evidence_lines.append(
            (
                f"- Title: {item.title}\n"
                f"  URL: {item.url}\n"
                f"  Date: "
                f"{item.published_at or 'unknown'}\n"
                f"  Snippet: "
                f"{item.snippet or ''}"
            )
        )

    evidence_text = "\n".join(
        evidence_lines
    )

    response = llm.invoke(
        [
            SystemMessage(
                content=WORKER_SYSTEM
            ),
            HumanMessage(
                content=(
                    f"Blog title:\n"
                    f"{plan.blog_title}\n\n"

                    f"Audience:\n"
                    f"{plan.audience}\n\n"

                    f"Tone:\n"
                    f"{plan.tone}\n\n"

                    f"Blog kind:\n"
                    f"{plan.blog_kind}\n\n"

                    f"Constraints:\n"
                    f"{plan.constraints}\n\n"

                    f"Topic:\n"
                    f"{topic}\n\n"

                    f"Mode:\n"
                    f"{mode}\n\n"

                    f"Section title:\n"
                    f"{task.title}\n\n"

                    f"Section type:\n"
                    f"{task.section_type}\n\n"

                    f"Goal:\n"
                    f"{task.goal}\n\n"

                    f"Brief:\n"
                    f"{task.brief}\n\n"

                    f"Target words:\n"
                    f"{task.target_words}\n\n"

                    f"Tags:\n"
                    f"{task.tags}\n\n"

                    f"requires_research:\n"
                    f"{task.requires_research}\n\n"

                    f"requires_citations:\n"
                    f"{task.requires_citations}\n\n"

                    f"requires_code:\n"
                    f"{task.requires_code}\n\n"

                    f"YOUR SECTION'S EXCLUSIVE BULLETS:\n"
                    f"{bullets_text}\n\n"

                    f"Must NOT cover:\n"
                    f"{must_not_cover_text or '- None specified'}\n\n"

                    "Evidence "
                    "(ONLY use these URLs when citing):\n"
                    f"{evidence_text}"
                )
            ),
        ]
    )

    # IMPORTANT GEMINI FIX:
    # response.content may be a list.
    section_md = _extract_response_text(
        response
    )

    if not section_md:

        raise ValueError(
            f"Worker {task.id} received an empty "
            "response from Gemini."
        )

    section_md = _clean_worker_section(
        section_md,
        task,
    )

    return (
        task.id,
        section_md,
    )


# ============================================================
# 14. PARALLEL WORKERS (LANGGRAPH FAN-OUT / FAN-IN)
# ============================================================

class WorkerState(TypedDict):
    """
    State received by one dynamically created worker branch.

    Each worker receives exactly one planned Task, while the
    parent ChatState keeps the shared blog-generation state.
    """

    plan: Plan

    task: Task

    topic: str

    mode: str

    evidence: List[EvidenceItem]


def worker_node(
    state: WorkerState,
) -> dict:
    """
    Generate exactly one blog section.

    LangGraph invokes this node once for every Task emitted by
    the fan-out function. The invocations can run concurrently.
    """

    payload = _build_worker_payload(
        plan=state["plan"],
        task=state["task"],
        topic=state["topic"],
        mode=state.get(
            "mode",
            "closed_book",
        ),
        evidence=state.get(
            "evidence",
            [],
        ),
    )

    task_id, section_md = _generate_worker_section(
        payload
    )

    return {
        "sections": [
            (
                task_id,
                section_md,
            )
        ]
    }


def fan_out_workers(
    state: ChatState,
) -> List[Send]:

    plan = state.get("plan")

    if plan is None:
        raise ValueError(
            "Cannot fan out workers because plan is None."
        )

    evidence = state.get(
        "evidence",
        [],
    )[:MAX_EVIDENCE_SOURCES]

    topic = state.get(
        "topic",
        "",
    )

    mode = state.get(
        "mode",
        "closed_book",
    )

    sends = []

    for task in plan.tasks:

        sends.append(
            Send(
                "worker",
                {
                    "plan": plan,
                    "task": task,
                    "topic": topic,
                    "mode": mode,
                    "evidence": evidence,
                },
            )
        )

    return sends

# ============================================================
# 15. FILENAME SANITIZATION
# ============================================================

def safe_filename(title: str) -> str:

    filename = re.sub(
        r'[<>:"/\\|?*]',
        "",
        title,
    )

    filename = filename.strip()

    if not filename:

        filename = "blog"

    return filename


# ============================================================
# 16. REDUCER
# ============================================================
def reducer(
    state: ChatState,
) -> dict:

    plan = state.get("plan")

    if plan is None:
        raise ValueError(
            "Cannot reduce because plan is None."
        )

    sections = state.get(
        "sections",
        []
    )

    # --------------------------------------------------------
    # 1. Build the expected task map
    # --------------------------------------------------------

    task_by_id = {
        task.id: task
        for task in plan.tasks
    }

    expected_ids = set(
        task_by_id.keys()
    )

    # --------------------------------------------------------
    # 2. Make sure every worker returned a valid result
    # --------------------------------------------------------

    returned_ids = [
        task_id
        for task_id, _ in sections
    ]

    returned_id_set = set(
        returned_ids
    )

    # --------------------------------------------------------
    # 3. Detect duplicate worker results
    # --------------------------------------------------------

    if len(returned_ids) != len(returned_id_set):

        duplicates = sorted(
            task_id
            for task_id in returned_id_set
            if returned_ids.count(task_id) > 1
        )

        raise ValueError(
            "Duplicate worker results detected for "
            f"task IDs: {duplicates}"
        )

    # --------------------------------------------------------
    # 4. Detect unknown worker results
    # --------------------------------------------------------

    unknown_ids = (
        returned_id_set
        - expected_ids
    )

    if unknown_ids:

        raise ValueError(
            "Worker returned unknown task IDs: "
            f"{sorted(unknown_ids)}"
        )

    # --------------------------------------------------------
    # 5. Detect missing worker results
    # --------------------------------------------------------

    missing_ids = (
        expected_ids
        - returned_id_set
    )

    if missing_ids:

        missing_titles = [
            task_by_id[task_id].title
            for task_id in sorted(
                missing_ids
            )
        ]

        raise ValueError(
            "Missing worker results for task IDs: "
            f"{sorted(missing_ids)}. "
            f"Missing sections: {missing_titles}"
        )

    # --------------------------------------------------------
    # 6. Validate worker content
    # --------------------------------------------------------

    for task_id, markdown in sections:

        if not isinstance(
            markdown,
            str
        ) or not markdown.strip():

            task_title = task_by_id[
                task_id
            ].title

            raise ValueError(
                "Worker returned empty content for "
                f"task {task_id}: '{task_title}'"
            )

    # --------------------------------------------------------
    # 7. Sort sections according to task ID
    # --------------------------------------------------------

    ordered_sections = []

    for task_id, markdown in sorted(
        sections,
        key=lambda item: item[0],
    ):

        task = task_by_id[
            task_id
        ]

        ordered_sections.append(
            f"## {task.title}\n\n"
            f"{markdown.strip()}"
        )

    # --------------------------------------------------------
    # 8. Assemble final blog
    # --------------------------------------------------------

    body = "\n\n".join(
        ordered_sections
    ).strip()

    return {
        "final_md": (
            f"# {plan.blog_title}\n\n"
            f"{body}\n"
        )
    }

# ============================================================
# 17. BUILD LANGGRAPH
# ============================================================

g = StateGraph(
    ChatState
)

g.add_node(
    "router",
    router_node,
)

g.add_node(
    "research",
    research_node,
)

g.add_node(
    "orchestrator",
    orchestrator_node,
)

# One reusable worker node is dynamically fanned out by
# `fan_out_workers`. LangGraph can execute the generated
# worker branches concurrently.
g.add_node(
    "worker",
    worker_node,
)

g.add_node(
    "reducer",
    reducer,
)


g.add_edge(
    START,
    "router",
)


g.add_conditional_edges(
    "router",
    route_next,
    {
        "research": "research",
        "orchestrator": "orchestrator",
    },
)


g.add_edge(
    "research",
    "orchestrator",
)


g.add_conditional_edges(
    "orchestrator",
    fan_out_workers,
)


g.add_edge(
    "worker",
    "reducer",
)


g.add_edge(
    "reducer",
    END,
)


app = g.compile()


# ============================================================
# 18. INITIAL STATE
# ============================================================

def _initial_state(
    topic: str,
) -> ChatState:

    return {
        "topic": topic,

        "mode": "",

        "needs_research": False,

        "queries": [],

        "evidence": [],

        "plan": None,

        "sections": [],

        "final_md": "",
    }


# ============================================================
# 19. NORMAL RUNNER
# ============================================================

def run(topic: str):

    topic = str(
        topic
    ).strip()

    if not topic:

        raise ValueError(
            "Topic cannot be empty."
        )

    return app.invoke(
        _initial_state(topic)
    )


# ============================================================
# 20. STREAMING RUNNER
# ============================================================

def run_stream(topic: str):
    """
    The worker LLM calls are fanned out by LangGraph.
    One worker branch is created for each section in the
    orchestrator's 5–7 section plan, allowing independent
    sections to be generated concurrently.
    """

    topic = str(
        topic
    ).strip()

    if not topic:

        raise ValueError(
            "Topic cannot be empty."
        )

    initial_state = _initial_state(
        topic
    )

    for event in app.stream(
        initial_state,
        stream_mode="updates",
    ):
        yield event


# ============================================================
# 21. CONVENIENCE FUNCTION
# ============================================================

def generate_blog(
    topic: str,
) -> str:

    result = run(topic)

    return result["final_md"]


# ============================================================
# 22. MAIN
# ============================================================

if __name__ == "__main__":

    topic = input(
        "Enter your blog topic: "
    ).strip()

    if not topic:

        print(
            "Please enter a valid blog topic."
        )

    else:

        print(
            "\nGenerating blog...\n"
        )

        result = run(topic)

        print(
            result["final_md"]
        )