from pathlib import Path
from typing import TypedDict, List, Annotated, Literal, Optional
import operator
import re
from urllib.parse import urlparse

from dotenv import load_dotenv
from pydantic import BaseModel, Field, ValidationError

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.messages import SystemMessage, HumanMessage
from langchain_community.tools.tavily_search import TavilySearchResults

from langgraph.graph import StateGraph, START, END


# ============================================================
# 1. ENVIRONMENT
# ============================================================

load_dotenv()


# ============================================================
# 2. CONFIGURATION
# ============================================================

MODEL_NAME = "gemini-3.1-flash-lite"

# IMPORTANT:
# Only this many useful sources are sent to the evidence
# synthesizer and later writing stages.
MAX_EVIDENCE_SOURCES = 12

# Research breadth. We can collect more than 12 raw results,
# rank them locally, and only send the best 12 to Gemini.
MAX_RESEARCH_QUERIES = 10
TAVILY_RESULTS_PER_QUERY = 4

# Keep snippets compact so prompts do not become unnecessarily
# large.
MAX_SNIPPET_CHARS = 900

# Sequential workers are intentional. Five simultaneous Gemini
# calls can cause provider-side rate-limit spikes.
WORKER_COUNT = 5


# ============================================================
# 3. LLM
# ============================================================

llm = ChatGoogleGenerativeAI(
    model=MODEL_NAME,
    temperature=0.7,
)


# ============================================================
# 4. PYDANTIC SCHEMAS
# ============================================================

class Task(BaseModel):
    """
    Represents one section/task of the blog.
    """

    id: int

    title: str

    goal: str = Field(
        ...,
        description=(
            "One sentence describing what the reader should "
            "be able to do or understand after this section."
        ),
    )

    bullets: List[str] = Field(
        ...,
        min_length=3,
        max_length=6,
        description=(
            "3–6 concrete, non-overlapping subpoints "
            "to cover in this section."
        ),
    )

    target_words: int = Field(
        ...,
        description="Target word count for this section.",
    )

    section_type: Literal[
        "intro",
        "core",
        "examples",
        "checklist",
        "common_mistakes",
        "conclusion",
    ] = Field(
        ...,
        description="Type of the blog section.",
    )

    brief: str = Field(
        ...,
        description="What this section should cover.",
    )

    tags: List[str] = Field(
        default_factory=list,
        description="Important tags/topics for this section.",
    )

    requires_research: bool = Field(
        default=False,
        description="Whether this section requires fresh research.",
    )

    requires_citations: bool = Field(
        default=False,
        description="Whether outside-world claims need citations.",
    )

    requires_code: bool = Field(
        default=False,
        description="Whether this section must contain a code example.",
    )


class Plan(BaseModel):
    """
    Complete blog plan generated by the orchestrator.
    """

    blog_title: str

    audience: str = Field(
        description="Who this blog is made for.",
    )

    tone: str = Field(
        description=(
            "Writing tone, for example practical, crisp, "
            "technical, beginner-friendly, etc."
        ),
    )

    blog_kind: Literal[
        "tutorial",
        "news_roundup",
    ] = Field(
        default="tutorial",
        description="The overall type of the blog.",
    )

    constraints: List[str] = Field(
        default_factory=list,
        description="Important constraints that apply to the blog.",
    )

    tasks: List[Task] = Field(
        ...,
        min_length=5,
        max_length=5,
        description="Exactly 5 sections/tasks for the blog.",
    )


class RouterDecision(BaseModel):
    """
    Decision produced by the routing node.
    """

    needs_research: bool

    mode: Literal[
        "closed_book",
        "hybrid",
        "open_book",
    ]

    queries: List[str] = Field(
        default_factory=list,
        max_length=10,
    )


class EvidenceItem(BaseModel):
    """
    One research source.
    """

    title: str

    url: str

    published_at: Optional[str] = None

    snippet: Optional[str] = None

    source: Optional[str] = None


class EvidencePack(BaseModel):
    """
    Collection of research sources.
    """

    evidence: List[EvidenceItem] = Field(
        default_factory=list,
        max_length=MAX_EVIDENCE_SOURCES,
    )


# ============================================================
# 5. LANGGRAPH STATE
# ============================================================

class ChatState(TypedDict):
    """
    Shared state used by the LangGraph workflow.
    """

    topic: str

    mode: str

    needs_research: bool

    queries: List[str]

    evidence: List[EvidenceItem]

    plan: Optional[Plan]

    sections: Annotated[
        List[tuple[int, str]],
        operator.add,
    ]

    final_md: str


# ============================================================
# 6. GEMINI RESPONSE HELPERS
# ============================================================

def _extract_response_text(response) -> str:
    """
    Normalize LangChain/Gemini response content into plain text.

    Gemini may expose response.content as:
    - a string
    - a list of content blocks
    - a list of strings
    - a list of dictionaries containing text
    - nested content structures
    """

    content = getattr(response, "content", response)

    if isinstance(content, str):
        return content.strip()

    if isinstance(content, list):

        parts: List[str] = []

        def collect(item) -> None:

            if isinstance(item, str):
                if item.strip():
                    parts.append(item)
                return

            if isinstance(item, dict):

                text_value = item.get("text")

                if isinstance(text_value, str):
                    if text_value.strip():
                        parts.append(text_value)
                    return

                nested = item.get("content")

                if isinstance(nested, str):
                    if nested.strip():
                        parts.append(nested)
                    return

                if isinstance(nested, list):
                    for nested_item in nested:
                        collect(nested_item)

                return

        for item in content:
            collect(item)

        return "\n".join(parts).strip()

    return str(content).strip()


def _invoke_structured(schema, messages):
    """
    Invoke Gemini using LangChain structured output.

    Gemini's structured-output path returns a Pydantic object.
    This helper also provides a useful error if the provider
    returns something unexpected.
    """

    structured_llm = llm.with_structured_output(
        schema
    )

    result = structured_llm.invoke(messages)

    if isinstance(result, schema):
        return result

    try:
        return schema.model_validate(result)
    except Exception as exc:
        raise ValueError(
            f"Gemini returned an unexpected structured-output "
            f"format for {schema.__name__}: {result!r}"
        ) from exc


# ============================================================
# 7. ROUTER
# ============================================================

ROUTER_SYSTEM = """
You are a routing module for a technical blog planner.

Decide whether web research is needed BEFORE planning.

Modes:

- closed_book:
  needs_research=false

  Evergreen topics where correctness does not depend on recent
  facts, such as concepts, fundamentals, algorithms, or general
  programming principles.

- hybrid:
  needs_research=true

  Mostly evergreen topics that benefit from up-to-date examples,
  tools, models, releases, libraries, or current best practices.

- open_book:
  needs_research=true

  Mostly volatile topics such as:
  weekly roundups,
  "this week",
  "latest",
  rankings,
  pricing,
  policy,
  regulation,
  current events.

If needs_research=true:

- Output 3–10 high-signal search queries.
- Queries must be specific and useful.
- Avoid generic queries such as just "AI" or "LLM".
- If the user asks for "latest", "this week", "last week",
  etc., reflect that constraint in the queries.

Return only the RouterDecision fields.
"""


def router_node(state: ChatState) -> dict:

    topic = state["topic"]

    decision = _invoke_structured(
        RouterDecision,
        [
            SystemMessage(
                content=ROUTER_SYSTEM
            ),
            HumanMessage(
                content=(
                    "User's blog topic:\n"
                    f"{topic}"
                )
            ),
        ],
    )

    queries = [
        q.strip()
        for q in decision.queries
        if isinstance(q, str) and q.strip()
    ][:MAX_RESEARCH_QUERIES]

    return {
        "needs_research": decision.needs_research,
        "mode": decision.mode,
        "queries": queries,
    }


def route_next(state: ChatState) -> str:

    if state["needs_research"]:
        return "research"

    return "orchestrator"


# ============================================================
# 8. TAVILY SEARCH
# ============================================================

def _compact_snippet(value: Optional[str]) -> str:

    if not value:
        return ""

    text = " ".join(
        str(value).split()
    )

    return text[:MAX_SNIPPET_CHARS]


def _domain_from_url(url: str) -> str:

    try:
        return (
            urlparse(url)
            .netloc
            .lower()
            .replace("www.", "")
        )
    except Exception:
        return ""


def _tavily_search(
    query: str,
    max_results: int = TAVILY_RESULTS_PER_QUERY,
) -> List[dict]:
    """
    Run one Tavily search and normalize the output.
    """

    tool = TavilySearchResults(
        max_results=max_results
    )

    results = tool.invoke(
        {
            "query": query
        }
    )

    normalized: List[dict] = []

    for result in results or []:

        if not isinstance(result, dict):
            continue

        url = str(
            result.get("url")
            or ""
        ).strip()

        if not url:
            continue

        normalized.append(
            {
                "title": str(
                    result.get("title")
                    or ""
                ).strip(),

                "url": url,

                "snippet": _compact_snippet(
                    result.get("content")
                    or result.get("snippet")
                    or ""
                ),

                "published_at": (
                    result.get("published_date")
                    or result.get("published_at")
                ),

                "source": (
                    result.get("source")
                    or _domain_from_url(url)
                ),
            }
        )

    return normalized


# ============================================================
# 9. DETERMINISTIC SOURCE RANKING
# ============================================================

def _source_authority_score(item: dict) -> int:
    """
    Lightweight deterministic authority scoring.

    This happens BEFORE the evidence synthesizer, so only the
    best ~10–15 sources ever reach the LLM.
    """

    url = item.get("url", "")

    domain = _domain_from_url(url)

    score = 0

    high_authority_domains = (
        ".gov",
        ".edu",
        "github.com",
        "arxiv.org",
        "openai.com",
        "developers.google.com",
        "ai.google.dev",
        "cloud.google.com",
        "python.org",
        "pytorch.org",
        "tensorflow.org",
        "microsoft.com",
        "aws.amazon.com",
        "anthropic.com",
        "meta.com",
        "developer.mozilla.org",
    )

    reputable_domains = (
        "reuters.com",
        "apnews.com",
        "bbc.com",
        "nytimes.com",
        "techcrunch.com",
        "theverge.com",
        "wired.com",
        "nature.com",
        "arstechnica.com",
    )

    if any(
        domain.endswith(suffix)
        for suffix in high_authority_domains
    ):
        score += 8

    if any(
        domain.endswith(suffix)
        for suffix in reputable_domains
    ):
        score += 5

    if item.get("published_at"):
        score += 1

    if item.get("snippet"):
        score += 2

    return score


def _rank_and_select_sources(
    raw_results: List[dict],
    topic: str,
    queries: List[str],
) -> List[dict]:
    """
    Deduplicate, score and select at most 12 sources.

    The full raw Tavily result set is NEVER passed to Gemini.
    """

    query_terms = set(
        re.findall(
            r"\b[a-zA-Z0-9][a-zA-Z0-9_-]{2,}\b",
            " ".join(
                [topic] + queries
            ).lower(),
        )
    )

    unique = {}

    for item in raw_results:

        url = item.get("url", "").strip()

        if not url:
            continue

        if url not in unique:
            unique[url] = item
            continue

        # Keep the richer duplicate.
        old = unique[url]

        if len(
            item.get("snippet", "")
        ) > len(
            old.get("snippet", "")
        ):
            unique[url] = item

    scored = []

    for item in unique.values():

        title = item.get(
            "title",
            "",
        ).lower()

        snippet = item.get(
            "snippet",
            "",
        ).lower()

        text = f"{title} {snippet}"

        overlap = sum(
            1
            for term in query_terms
            if term in text
        )

        score = (
            overlap * 2
            + _source_authority_score(item)
        )

        scored.append(
            (
                score,
                item,
            )
        )

    scored.sort(
        key=lambda pair: (
            pair[0],
            len(
                pair[1].get(
                    "snippet",
                    "",
                )
            ),
        ),
        reverse=True,
    )

    return [
        item
        for _, item in scored[
            :MAX_EVIDENCE_SOURCES
        ]
    ]


# ============================================================
# 10. RESEARCH
# ============================================================

RESEARCH_SYSTEM = """
You are a research synthesizer for technical writing.

You are given ONLY the most useful web sources selected by a
deterministic ranking stage.

Create an EvidencePack from those sources.

Rules:

- Preserve the supplied URLs exactly.
- Only include items with a non-empty URL.
- Do not invent URLs.
- Prefer relevant and authoritative sources.
- Prefer official documentation, company sources,
  research papers, government sources, and reputable
  publications when available.
- Preserve an explicitly supplied publication date.
- Never guess a publication date.
- Keep snippets concise.
- Do not create additional sources.
- Deduplicate by URL.
- Return at most 12 evidence items.

Return only the EvidencePack fields.
"""


def research_node(state: ChatState) -> dict:
    """
    Search Tavily, rank locally, and send ONLY the best 12
    sources to Gemini.
    """

    queries = (
        state.get(
            "queries",
            [],
        )
        or []
    )[:MAX_RESEARCH_QUERIES]

    raw_results: List[dict] = []

    for query in queries:

        try:

            results = _tavily_search(
                query,
                max_results=TAVILY_RESULTS_PER_QUERY,
            )

            raw_results.extend(results)

        except Exception as exc:

            print(
                f"Research failed for query "
                f"'{query}': {exc}"
            )

    if not raw_results:

        return {
            "evidence": []
        }

    selected_sources = _rank_and_select_sources(
        raw_results=raw_results,
        topic=state["topic"],
        queries=queries,
    )

    # IMPORTANT:
    # Only selected_sources (max 12) are passed to Gemini.
    compact_sources = []

    for item in selected_sources:

        compact_sources.append(
            {
                "title": item.get(
                    "title",
                    "",
                ),

                "url": item.get(
                    "url",
                    "",
                ),

                "snippet": item.get(
                    "snippet",
                    "",
                ),

                "published_at": item.get(
                    "published_at"
                ),

                "source": item.get(
                    "source"
                ),
            }
        )

    pack = _invoke_structured(
        EvidencePack,
        [
            SystemMessage(
                content=RESEARCH_SYSTEM
            ),
            HumanMessage(
                content=(
                    "Topic:\n"
                    f"{state['topic']}\n\n"
                    "Selected source candidates "
                    f"(maximum {MAX_EVIDENCE_SOURCES}):\n"
                    f"{compact_sources}"
                )
            ),
        ],
    )

    # Final deterministic URL deduplication + hard cap.
    dedup = {}

    for item in pack.evidence:

        if item.url:

            dedup[
                item.url
            ] = item

    final_evidence = list(
        dedup.values()
    )[
        :MAX_EVIDENCE_SOURCES
    ]

    return {
        "evidence": final_evidence
    }


# ============================================================
# 11. ORCHESTRATOR
# ============================================================

ORCH_MESSAGE = """
You are a senior technical writer and developer advocate.

Your job is to produce a highly actionable outline for a
technical blog post.

HARD REQUIREMENTS:

- Create EXACTLY 5 sections/tasks.
- Every task must include:
    1. id
    2. title
    3. goal
    4. 3 concrete bullets
    5. target word count
    6. section_type
    7. brief
    8. tags
    9. requires_research
    10. requires_citations
    11. requires_code

QUALITY BAR:

- Assume the reader is a developer.
- Use correct technical terminology.
- Bullets must be actionable.
- Prefer:
    build
    compare
    measure
    verify
    debug

The overall plan should include at least TWO of these:

- minimal code sketch / MWE
- edge cases / failure modes
- performance/cost considerations
- security/privacy considerations when relevant
- debugging/observability tips

CODE REQUIREMENT:

At least one section should normally have:

requires_code = true

RESEARCH REQUIREMENT:

For hybrid mode:

- Use evidence for current examples, tools, models,
  releases, libraries, or other fresh information.
- Mark relevant sections:
    requires_research = true
    requires_citations = true

For open_book mode:

- Set blog_kind = "news_roundup".
- Every section should summarize events and implications.
- Do NOT create tutorial/how-to sections unless the user
  explicitly asked for a tutorial.
- If evidence is empty or insufficient, state that clearly
  in the plan.

For closed_book mode:

- Keep the content evergreen.
- Do not depend on fresh evidence.

SECTION TYPES:

Use suitable section types from:

intro
core
examples
checklist
common_mistakes
conclusion

Use "common_mistakes" exactly once.

Prefer using "intro" for section 1 and "conclusion" for
section 5 when appropriate.

Return only the Plan fields.
"""


def validate_plan(plan: Plan) -> Plan:

    if len(plan.tasks) != 5:

        raise ValueError(
            f"Expected exactly 5 tasks, "
            f"got {len(plan.tasks)}"
        )

    task_ids = [
        task.id
        for task in plan.tasks
    ]

    if len(set(task_ids)) != len(task_ids):

        raise ValueError(
            "Task IDs must be unique."
        )

    common_mistakes_count = sum(
        task.section_type
        == "common_mistakes"
        for task in plan.tasks
    )

    if common_mistakes_count != 1:

        raise ValueError(
            "Plan must contain exactly one "
            "'common_mistakes' section."
        )

    return plan


def orchestrator_node(
    state: ChatState,
) -> dict:

    evidence = state.get(
        "evidence",
        []
    )

    # Never pass more than the selected 12 sources.
    evidence_for_prompt = [
        item.model_dump()
        for item in evidence[
            :MAX_EVIDENCE_SOURCES
        ]
    ]

    mode = state.get(
        "mode",
        "closed_book",
    )

    plan = _invoke_structured(
        Plan,
        [
            SystemMessage(
                content=ORCH_MESSAGE
            ),
            HumanMessage(
                content=(
                    f"Topic:\n"
                    f"{state['topic']}\n\n"

                    f"Mode:\n"
                    f"{mode}\n\n"

                    "Evidence "
                    "(ONLY use for fresh claims; "
                    "may be empty):\n"
                    f"{evidence_for_prompt}"
                )
            ),
        ],
    )

    plan = validate_plan(plan)

    return {
        "plan": plan
    }


# ============================================================
# 12. WORKER PROMPT
# ============================================================

WORKER_SYSTEM = """
You are a senior technical writer and developer advocate.

Write ONE section of a technical blog post in Markdown.

HARD CONSTRAINTS:

- Follow the provided Goal.
- Cover ALL bullets in order.
- Do not skip bullets.
- Do not merge unrelated bullets.
- Stay close to the target word count (±15%).
- Output ONLY the section content in Markdown.
- Do NOT output a blog title H1.
- Start with:

## <Section Title>

SCOPE GUARD:

If blog_kind == "news_roundup":

- Do NOT turn the section into a tutorial.
- Do NOT teach web scraping, RSS, automation,
  or news fetching unless explicitly requested.
- Focus on events and implications.

GROUNDING POLICY:

If mode == "open_book":

- Do NOT introduce a specific event, company, model,
  funding, policy, release, ranking, or other current
  claim unless supported by the provided evidence URLs.
- For supported outside-world claims, attach citations
  as Markdown links:

  ([Source](URL))

- Only use URLs from the provided evidence.
- If something cannot be supported, write:

  "Not found in provided sources."

If requires_citations == true:

- Cite outside-world claims using only the provided
  Evidence URLs.

Evergreen reasoning does not require citations unless
requires_citations is true.

CODE:

If requires_code == true:

- Include at least one minimal and correct code snippet
  relevant to the section bullets.

STYLE:

- Short paragraphs.
- Use bullets where helpful.
- Use code fences for code.
- Avoid fluff and marketing language.
- Be precise.
- Be implementation-oriented.
"""


# ============================================================
# 13. WORKER HELPERS
# ============================================================

def _build_worker_payload(
    plan: Plan,
    task: Task,
    topic: str,
    mode: str,
    evidence: List[EvidenceItem],
) -> dict:

    return {
        "plan": plan.model_dump(),
        "topic": topic,
        "task": task.model_dump(),
        "mode": mode,
        "evidence": [
            item.model_dump()
            for item in evidence[
                :MAX_EVIDENCE_SOURCES
            ]
        ],
    }


def _generate_worker_section(
    payload: dict,
) -> tuple[int, str]:

    task = Task(
        **payload["task"]
    )

    plan = Plan(
        **payload["plan"]
    )

    evidence = [
        EvidenceItem(**item)
        for item in payload.get(
            "evidence",
            []
        )[
            :MAX_EVIDENCE_SOURCES
        ]
    ]

    topic = payload["topic"]

    mode = payload.get(
        "mode",
        "closed_book",
    )

    bullets_text = "\n".join(
        f"- {bullet}"
        for bullet in task.bullets
    )

    evidence_lines = []

    for item in evidence:

        evidence_lines.append(
            (
                f"- Title: {item.title}\n"
                f"  URL: {item.url}\n"
                f"  Date: "
                f"{item.published_at or 'unknown'}\n"
                f"  Snippet: "
                f"{item.snippet or ''}"
            )
        )

    evidence_text = "\n".join(
        evidence_lines
    )

    response = llm.invoke(
        [
            SystemMessage(
                content=WORKER_SYSTEM
            ),
            HumanMessage(
                content=(
                    f"Blog title:\n"
                    f"{plan.blog_title}\n\n"

                    f"Audience:\n"
                    f"{plan.audience}\n\n"

                    f"Tone:\n"
                    f"{plan.tone}\n\n"

                    f"Blog kind:\n"
                    f"{plan.blog_kind}\n\n"

                    f"Constraints:\n"
                    f"{plan.constraints}\n\n"

                    f"Topic:\n"
                    f"{topic}\n\n"

                    f"Mode:\n"
                    f"{mode}\n\n"

                    f"Section title:\n"
                    f"{task.title}\n\n"

                    f"Section type:\n"
                    f"{task.section_type}\n\n"

                    f"Goal:\n"
                    f"{task.goal}\n\n"

                    f"Brief:\n"
                    f"{task.brief}\n\n"

                    f"Target words:\n"
                    f"{task.target_words}\n\n"

                    f"Tags:\n"
                    f"{task.tags}\n\n"

                    f"requires_research:\n"
                    f"{task.requires_research}\n\n"

                    f"requires_citations:\n"
                    f"{task.requires_citations}\n\n"

                    f"requires_code:\n"
                    f"{task.requires_code}\n\n"

                    f"Bullets:\n"
                    f"{bullets_text}\n\n"

                    "Evidence "
                    "(ONLY use these URLs when citing):\n"
                    f"{evidence_text}"
                )
            ),
        ]
    )

    # IMPORTANT GEMINI FIX:
    # response.content may be a list.
    section_md = _extract_response_text(
        response
    )

    if not section_md:

        raise ValueError(
            f"Worker {task.id} received an empty "
            "response from Gemini."
        )

    return (
        task.id,
        section_md,
    )


# ============================================================
# 14. SEQUENTIAL WORKERS
# ============================================================

def workers_node(
    state: ChatState,
) -> dict:
    """
    Generate all five sections sequentially.

    This replaces LangGraph Send/fan-out so that five Gemini
    requests are NOT launched concurrently.

    The worker count remains exactly five.
    """

    plan = state.get(
        "plan"
    )

    if plan is None:

        raise ValueError(
            "Cannot run workers because plan is None."
        )

    tasks = plan.tasks

    if len(tasks) != WORKER_COUNT:

        raise ValueError(
            f"Expected {WORKER_COUNT} tasks, "
            f"got {len(tasks)}"
        )

    evidence = state.get(
        "evidence",
        []
    )[
        :MAX_EVIDENCE_SOURCES
    ]

    sections = []

    for task in tasks:

        payload = _build_worker_payload(
            plan=plan,
            task=task,
            topic=state["topic"],
            mode=state.get(
                "mode",
                "closed_book",
            ),
            evidence=evidence,
        )

        task_id, section_md = (
            _generate_worker_section(
                payload
            )
        )

        sections.append(
            (
                task_id,
                section_md,
            )
        )

    return {
        "sections": sections
    }


# ============================================================
# 15. FILENAME SANITIZATION
# ============================================================

def safe_filename(title: str) -> str:

    filename = re.sub(
        r'[<>:"/\\|?*]',
        "",
        title,
    )

    filename = filename.strip()

    if not filename:

        filename = "blog"

    return filename


# ============================================================
# 16. REDUCER
# ============================================================

def reducer(
    state: ChatState,
) -> dict:
    """
    Combine the five worker sections in task-ID order and
    create the final Markdown file.
    """

    plan = state.get(
        "plan"
    )

    if plan is None:

        raise ValueError(
            "Cannot reduce because plan is None."
        )

    sections = state.get(
        "sections",
        []
    )

    ordered_sections = [
        markdown
        for _, markdown
        in sorted(
            sections,
            key=lambda item: item[0],
        )
    ]

    body = "\n\n".join(
        ordered_sections
    ).strip()

    final_md = (
        f"# {plan.blog_title}\n\n"
        f"{body}\n"
    )

    filename = (
        f"{safe_filename(plan.blog_title)}.md"
    )

    Path(filename).write_text(
        final_md,
        encoding="utf-8",
    )

    return {
        "final_md": final_md
    }


# ============================================================
# 17. BUILD LANGGRAPH
# ============================================================

g = StateGraph(
    ChatState
)

g.add_node(
    "router",
    router_node,
)

g.add_node(
    "research",
    research_node,
)

g.add_node(
    "orchestrator",
    orchestrator_node,
)

# One node executes the five workers sequentially.
g.add_node(
    "workers",
    workers_node,
)

g.add_node(
    "reducer",
    reducer,
)


g.add_edge(
    START,
    "router",
)


g.add_conditional_edges(
    "router",
    route_next,
    {
        "research": "research",
        "orchestrator": "orchestrator",
    },
)


g.add_edge(
    "research",
    "orchestrator",
)


g.add_edge(
    "orchestrator",
    "workers",
)


g.add_edge(
    "workers",
    "reducer",
)


g.add_edge(
    "reducer",
    END,
)


app = g.compile()


# ============================================================
# 18. INITIAL STATE
# ============================================================

def _initial_state(
    topic: str,
) -> ChatState:

    return {
        "topic": topic,

        "mode": "",

        "needs_research": False,

        "queries": [],

        "evidence": [],

        "plan": None,

        "sections": [],

        "final_md": "",
    }


# ============================================================
# 19. NORMAL RUNNER
# ============================================================

def run(topic: str):

    topic = str(
        topic
    ).strip()

    if not topic:

        raise ValueError(
            "Topic cannot be empty."
        )

    return app.invoke(
        _initial_state(topic)
    )


# ============================================================
# 20. STREAMING RUNNER
# ============================================================

def run_stream(topic: str):
    """
    Stream LangGraph node updates.

    The graph itself is streamed at node level.
    The five worker LLM calls are intentionally sequential
    inside the workers node.
    """

    topic = str(
        topic
    ).strip()

    if not topic:

        raise ValueError(
            "Topic cannot be empty."
        )

    initial_state = _initial_state(
        topic
    )

    for event in app.stream(
        initial_state,
        stream_mode="updates",
    ):
        yield event


# ============================================================
# 21. CONVENIENCE FUNCTION
# ============================================================

def generate_blog(
    topic: str,
) -> str:

    result = run(topic)

    return result["final_md"]


# ============================================================
# 22. MAIN
# ============================================================

if __name__ == "__main__":

    topic = input(
        "Enter your blog topic: "
    ).strip()

    if not topic:

        print(
            "Please enter a valid blog topic."
        )

    else:

        print(
            "\nGenerating blog...\n"
        )

        result = run(topic)

        print(
            result["final_md"]
        )
