"""
Export utilities for the Blog Writing Agent.

This module is responsible for converting the final Markdown
blog generated by the backend into different downloadable
formats.

Supported formats will be added incrementally:

1. Markdown (.md)
2. Plain Text (.txt)
3. HTML (.html)
4. Word (.docx)
5. PDF (.pdf)

The Streamlit frontend should only call these utilities.
File-format conversion logic should remain outside frontend.py.
"""

import re
from io import BytesIO


# ============================================================
# 1. FILENAME UTILITIES
# ============================================================

def sanitize_filename(title: str) -> str:
    """
    Convert a blog title into a safe filename.

    Removes characters that are invalid in Windows filenames
    and performs basic cleanup.
    """

    title = str(title).strip()

    # Characters forbidden by Windows filenames.
    filename = re.sub(
        r'[<>:"/\\|?*]',
        "",
        title,
    )

    # Replace repeated whitespace with a single space.
    filename = re.sub(
        r"\s+",
        " ",
        filename,
    ).strip()

    # Windows does not allow filenames ending in
    # spaces or periods.
    filename = filename.rstrip(
        ". "
    )

    if not filename:
        filename = "blog"

    return filename


# ============================================================
# 2. BLOG TITLE EXTRACTION
# ============================================================

def extract_blog_title(
    markdown_content: str,
) -> str:
    """
    Extract the blog title from the first Markdown H1.

    Example:

        # Building AI Agents with LangGraph

    becomes:

        Building AI Agents with LangGraph

    If no H1 is found, 'blog' is returned.
    """

    if not markdown_content:
        return "blog"

    for line in markdown_content.splitlines():

        line = line.strip()

        if line.startswith("# "):

            title = line[2:].strip()

            if title:
                return title

    return "blog"


# ============================================================
# 3. EXPORT FILENAME
# ============================================================

def build_export_filename(
    markdown_content: str,
    extension: str,
) -> str:
    """
    Build a safe filename for an exported blog.

    Example:

        Building AI Agents with LangGraph.md
        Building AI Agents with LangGraph.pdf
    """

    title = extract_blog_title(
        markdown_content
    )

    safe_title = sanitize_filename(
        title
    )

    extension = (
        str(extension)
        .strip()
        .lstrip(".")
        .lower()
    )

    if not extension:
        raise ValueError(
            "Export extension cannot be empty."
        )

    return (
        f"{safe_title}.{extension}"
    )

# ============================================================
# 4. MARKDOWN EXPORT
# ============================================================

def export_markdown(
    markdown_content: str,
) -> tuple[str, str]:
    """
    Export the blog as Markdown.

    Returns:
        tuple[str, str]:
            - Markdown content
            - Suggested filename
    """

    if not markdown_content or not markdown_content.strip():
        raise ValueError(
            "Markdown content cannot be empty."
        )

    filename = build_export_filename(
        markdown_content,
        "md",
    )

    return (
        markdown_content,
        filename,
    )


# ============================================================
# 5. PLAIN TEXT EXPORT
# ============================================================

def export_text(
    markdown_content: str,
) -> tuple[str, str]:
    """
    Convert the Markdown blog into plain text.

    Markdown formatting such as:
        # headings
        **bold**
        *italic*
        [links](url)
        ```code```

    is removed or simplified so the result can be read
    as normal plain text.
    """

    if not markdown_content or not markdown_content.strip():
        raise ValueError(
            "Markdown content cannot be empty."
        )

    text = markdown_content

    # --------------------------------------------------------
    # Remove fenced code block markers while preserving code.
    # --------------------------------------------------------

    text = re.sub(
        r"```[a-zA-Z0-9_+-]*\n?",
        "",
        text,
    )

    text = text.replace(
        "```",
        "",
    )

    # --------------------------------------------------------
    # Convert Markdown headings to plain text.
    #
    # Example:
    #     ## Introduction
    #
    # becomes:
    #     Introduction
    # --------------------------------------------------------

    text = re.sub(
        r"^\s{0,3}#{1,6}\s+",
        "",
        text,
        flags=re.MULTILINE,
    )

    # --------------------------------------------------------
    # Convert Markdown links.
    #
    # Example:
    #     [LangGraph](https://example.com)
    #
    # becomes:
    #     LangGraph
    # --------------------------------------------------------

    text = re.sub(
        r"\[([^\]]+)\]\([^)]+\)",
        r"\1",
        text,
    )

    # --------------------------------------------------------
    # Remove bold / italic / strikethrough markers.
    # --------------------------------------------------------

    text = re.sub(
        r"\*\*(.*?)\*\*",
        r"\1",
        text,
    )

    text = re.sub(
        r"__(.*?)__",
        r"\1",
        text,
    )

    text = re.sub(
        r"(?<!\*)\*(?!\s)(.*?)(?<!\s)\*(?!\*)",
        r"\1",
        text,
    )

    text = re.sub(
        r"(?<!_)_(?!\s)(.*?)(?<!\s)_(?!_)",
        r"\1",
        text,
    )

    text = re.sub(
        r"~~(.*?)~~",
        r"\1",
        text,
    )

    # --------------------------------------------------------
    # Remove inline code markers.
    #
    # Example:
    #     `StateGraph`
    #
    # becomes:
    #     StateGraph
    # --------------------------------------------------------

    text = re.sub(
        r"`([^`]+)`",
        r"\1",
        text,
    )

    # --------------------------------------------------------
    # Remove blockquote markers.
    # --------------------------------------------------------

    text = re.sub(
        r"^\s*>\s?",
        "",
        text,
        flags=re.MULTILINE,
    )

    # --------------------------------------------------------
    # Convert unordered Markdown bullets into simple bullets.
    # --------------------------------------------------------

    text = re.sub(
        r"^\s*[-*+]\s+",
        "• ",
        text,
        flags=re.MULTILINE,
    )

    # --------------------------------------------------------
    # Remove ordered-list Markdown formatting.
    #
    # Keep the numbers because they are useful in plain text.
    # --------------------------------------------------------

    text = re.sub(
        r"^\s*(\d+)\.\s+",
        r"\1. ",
        text,
        flags=re.MULTILINE,
    )

    # --------------------------------------------------------
    # Remove excessive horizontal-rule formatting.
    # --------------------------------------------------------

    text = re.sub(
        r"^\s*([-*_])(?:\s*\1){2,}\s*$",
        "",
        text,
        flags=re.MULTILINE,
    )

    # --------------------------------------------------------
    # Normalize excessive blank lines.
    # --------------------------------------------------------

    text = re.sub(
        r"\n{3,}",
        "\n\n",
        text,
    )

    return (
        text.strip() + "\n",
        build_export_filename(
            markdown_content,
            "txt",
        ),
    )


# ============================================================
# 6. HTML EXPORT
# ============================================================

def export_html(
    markdown_content: str,
) -> tuple[str, str]:
    """
    Convert the Markdown blog into a complete HTML document.

    The resulting HTML includes:

        - UTF-8 character encoding
        - Responsive layout
        - Blog typography
        - Styled code blocks
        - Styled blockquotes
        - Lists
        - Links

    Markdown is converted using the 'markdown' Python package.
    """

    if not markdown_content or not markdown_content.strip():
        raise ValueError(
            "Markdown content cannot be empty."
        )

    try:
        import markdown
    except ImportError as exc:
        raise ImportError(
            "The 'markdown' package is required "
            "for HTML export. Install it with: "
            "pip install markdown"
        ) from exc

    # --------------------------------------------------------
    # Convert Markdown → HTML body.
    # --------------------------------------------------------

    html_body = markdown.markdown(
        markdown_content,
        extensions=[
            "fenced_code",
            "tables",
            "nl2br",
        ],
    )

    # --------------------------------------------------------
    # Create a complete standalone HTML document.
    # --------------------------------------------------------

    title = extract_blog_title(
        markdown_content
    )

    escaped_title = (
        title.replace(
            "&",
            "&amp;",
        )
        .replace(
            "<",
            "&lt;",
        )
        .replace(
            ">",
            "&gt;",
        )
        .replace(
            '"',
            "&quot;",
        )
    )

    html_document = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta
        name="viewport"
        content="width=device-width, initial-scale=1.0"
    >
    <title>{escaped_title}</title>

    <style>
        body {{
            max-width: 900px;
            margin: 0 auto;
            padding: 40px 24px;
            font-family:
                -apple-system,
                BlinkMacSystemFont,
                "Segoe UI",
                sans-serif;
            line-height: 1.7;
            color: #222;
            background: #fff;
        }}

        h1 {{
            font-size: 2.4rem;
            line-height: 1.2;
            margin-bottom: 1.5rem;
        }}

        h2 {{
            margin-top: 2.5rem;
        }}

        h3 {{
            margin-top: 2rem;
        }}

        p {{
            margin: 1rem 0;
        }}

        ul,
        ol {{
            padding-left: 2rem;
        }}

        li {{
            margin: 0.4rem 0;
        }}

        blockquote {{
            margin: 1.5rem 0;
            padding: 0.8rem 1.2rem;
            border-left: 4px solid #999;
            background: #f5f5f5;
        }}

        pre {{
            overflow-x: auto;
            padding: 1rem;
            border-radius: 8px;
            background: #f4f4f4;
        }}

        code {{
            font-family:
                "Cascadia Code",
                "Fira Code",
                Consolas,
                monospace;
        }}

        :not(pre) > code {{
            padding: 0.15rem 0.35rem;
            border-radius: 4px;
            background: #f0f0f0;
        }}

        table {{
            width: 100%;
            border-collapse: collapse;
            margin: 1.5rem 0;
        }}

        th,
        td {{
            padding: 0.7rem;
            border: 1px solid #ddd;
            text-align: left;
        }}

        th {{
            font-weight: 600;
            background: #f5f5f5;
        }}

        a {{
            text-decoration: none;
        }}

        img {{
            max-width: 100%;
            height: auto;
        }}
    </style>
</head>

<body>
    {html_body}
</body>
</html>
"""

    return (
        html_document,
        build_export_filename(
            markdown_content,
            "html",
        ),
    )


    # ============================================================
# 7. DOCX EXPORT
# ============================================================

def export_docx(
    markdown_content: str,
) -> tuple[bytes, str]:
    """
    Convert the Markdown blog into a Microsoft Word document.

    Returns:
        tuple[bytes, str]:
            - DOCX file as bytes
            - Suggested filename
    """

    if not markdown_content or not markdown_content.strip():
        raise ValueError(
            "Markdown content cannot be empty."
        )

    try:
        from io import BytesIO

        from docx import Document
        from docx.enum.text import WD_ALIGN_PARAGRAPH
        from docx.enum.style import WD_STYLE_TYPE
        from docx.shared import Inches, Pt

    except ImportError as exc:
        raise ImportError(
            "The 'python-docx' package is required "
            "for DOCX export. Install it with: "
            "pip install python-docx"
        ) from exc

    # --------------------------------------------------------
    # Create document
    # --------------------------------------------------------

    document = Document()

    # --------------------------------------------------------
    # Page setup
    # --------------------------------------------------------

    section = document.sections[0]

    section.top_margin = Inches(0.8)
    section.bottom_margin = Inches(0.8)
    section.left_margin = Inches(0.85)
    section.right_margin = Inches(0.85)

    # --------------------------------------------------------
    # Normal paragraph style
    # --------------------------------------------------------

    normal_style = document.styles["Normal"]

    normal_style.font.name = "Aptos"
    normal_style.font.size = Pt(11)

    # --------------------------------------------------------
    # Create a code style
    # --------------------------------------------------------

    if "Blog Code" not in [
        style.name for style in document.styles
    ]:

        code_style = document.styles.add_style(
            "Blog Code",
            WD_STYLE_TYPE.PARAGRAPH,
        )

        code_style.font.name = "Consolas"
        code_style.font.size = Pt(9)

    # --------------------------------------------------------
    # Helper: add inline formatted text
    # --------------------------------------------------------

    def add_inline_text(
        paragraph,
        text: str,
    ):
        """
        Add a Markdown paragraph while preserving
        basic inline formatting:

            **bold**
            *italic*
            `code`
        """

        pattern = re.compile(
            r"(\*\*.*?\*\*|__.*?__|`.*?`|\*.*?\*|_.*?_)"
        )

        parts = pattern.split(text)

        for part in parts:

            if not part:
                continue

            # Bold
            if (
                part.startswith("**")
                and part.endswith("**")
            ) or (
                part.startswith("__")
                and part.endswith("__")
            ):

                run = paragraph.add_run(
                    part[2:-2]
                )

                run.bold = True

            # Inline code
            elif (
                part.startswith("`")
                and part.endswith("`")
            ):

                run = paragraph.add_run(
                    part[1:-1]
                )

                run.font.name = "Consolas"
                run.font.size = Pt(9)

            # Italic
            elif (
                part.startswith("*")
                and part.endswith("*")
            ) or (
                part.startswith("_")
                and part.endswith("_")
            ):

                run = paragraph.add_run(
                    part[1:-1]
                )

                run.italic = True

            else:

                paragraph.add_run(part)

    # --------------------------------------------------------
    # Process Markdown line-by-line
    # --------------------------------------------------------

    lines = markdown_content.splitlines()

    inside_code_block = False
    code_lines = []

    for line in lines:

        stripped = line.strip()

        # ----------------------------------------------------
        # Fenced code block
        # ----------------------------------------------------

        if stripped.startswith("```"):

            if not inside_code_block:

                inside_code_block = True
                code_lines = []

            else:

                inside_code_block = False

                code_paragraph = document.add_paragraph(
                    style="Blog Code"
                )

                code_paragraph.paragraph_format.space_before = Pt(6)
                code_paragraph.paragraph_format.space_after = Pt(6)

                code_paragraph.add_run(
                    "\n".join(code_lines)
                )

                code_lines = []

            continue

        if inside_code_block:

            code_lines.append(line)

            continue

        # ----------------------------------------------------
        # Empty line
        # ----------------------------------------------------

        if not stripped:

            continue

        # ----------------------------------------------------
        # Heading 1
        # ----------------------------------------------------

        if re.match(
            r"^#\s+",
            stripped,
        ):

            heading_text = re.sub(
                r"^#\s+",
                "",
                stripped,
            )

            paragraph = document.add_heading(
                heading_text,
                level=1,
            )

            paragraph.alignment = (
                WD_ALIGN_PARAGRAPH.LEFT
            )

            continue

        # ----------------------------------------------------
        # Heading 2
        # ----------------------------------------------------

        if re.match(
            r"^##\s+",
            stripped,
        ):

            heading_text = re.sub(
                r"^##\s+",
                "",
                stripped,
            )

            document.add_heading(
                heading_text,
                level=2,
            )

            continue

        # ----------------------------------------------------
        # Heading 3
        # ----------------------------------------------------

        if re.match(
            r"^###\s+",
            stripped,
        ):

            heading_text = re.sub(
                r"^###\s+",
                "",
                stripped,
            )

            document.add_heading(
                heading_text,
                level=3,
            )

            continue

        # ----------------------------------------------------
        # Heading 4–6
        # ----------------------------------------------------

        heading_match = re.match(
            r"^(#{4,6})\s+(.+)",
            stripped,
        )

        if heading_match:

            level = min(
                len(heading_match.group(1)),
                6,
            )

            document.add_heading(
                heading_match.group(2),
                level=level,
            )

            continue

        # ----------------------------------------------------
        # Unordered list
        # ----------------------------------------------------

        bullet_match = re.match(
            r"^[-*+]\s+(.+)",
            stripped,
        )

        if bullet_match:

            paragraph = document.add_paragraph(
                style="List Bullet"
            )

            add_inline_text(
                paragraph,
                bullet_match.group(1),
            )

            continue

        # ----------------------------------------------------
        # Ordered list
        # ----------------------------------------------------

        numbered_match = re.match(
            r"^\d+\.\s+(.+)",
            stripped,
        )

        if numbered_match:

            paragraph = document.add_paragraph(
                style="List Number"
            )

            add_inline_text(
                paragraph,
                numbered_match.group(1),
            )

            continue

        # ----------------------------------------------------
        # Blockquote
        # ----------------------------------------------------

        quote_match = re.match(
            r"^>\s?(.*)",
            stripped,
        )

        if quote_match:

            paragraph = document.add_paragraph()

            paragraph.paragraph_format.left_indent = (
                Inches(0.3)
            )

            run = paragraph.add_run(
                quote_match.group(1)
            )

            run.italic = True

            continue

        # ----------------------------------------------------
        # Horizontal rule
        # ----------------------------------------------------

        if re.match(
            r"^([-*_])(?:\s*\1){2,}$",
            stripped,
        ):

            paragraph = document.add_paragraph()

            paragraph.add_run(
                "────────────────────────"
            )

            continue

        # ----------------------------------------------------
        # Normal paragraph
        # ----------------------------------------------------

        paragraph = document.add_paragraph()

        paragraph.paragraph_format.space_after = Pt(8)
        paragraph.paragraph_format.line_spacing = 1.15

        add_inline_text(
            paragraph,
            stripped,
        )

    # --------------------------------------------------------
    # Save document into memory
    # --------------------------------------------------------

    buffer = BytesIO()

    document.save(buffer)

    buffer.seek(0)

    filename = build_export_filename(
        markdown_content,
        "docx",
    )

    return (
        buffer.getvalue(),
        filename,
    )

# ============================================================
# 8. PDF EXPORT
# ============================================================

def export_pdf(
    markdown_content: str,
) -> tuple[bytes, str]:
    """
    Convert the Markdown blog into a PDF document.

    Returns:
        tuple[bytes, str]:
            - PDF file as bytes
            - Suggested filename
    """

    if not markdown_content or not markdown_content.strip():
        raise ValueError(
            "Markdown content cannot be empty."
        )

    try:
        from xml.sax.saxutils import escape

        from reportlab.lib.enums import TA_LEFT
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import (
            ParagraphStyle,
            getSampleStyleSheet,
        )
        from reportlab.lib.units import inch
        from reportlab.platypus import (
            HRFlowable,
            ListFlowable,
            ListItem,
            Paragraph,
            Preformatted,
            SimpleDocTemplate,
            Spacer,
        )

    except ImportError as exc:
        raise ImportError(
            "The 'reportlab' package is required "
            "for PDF export. Install it with: "
            "pip install reportlab"
        ) from exc

    # --------------------------------------------------------
    # Create PDF in memory
    # --------------------------------------------------------

    buffer = BytesIO()

    document = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=0.75 * inch,
        leftMargin=0.75 * inch,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
        title=extract_blog_title(
            markdown_content
        ),
    )

    # --------------------------------------------------------
    # Styles
    # --------------------------------------------------------

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "BlogTitle",
        parent=styles["Title"],
        fontName="Helvetica-Bold",
        fontSize=24,
        leading=29,
        alignment=TA_LEFT,
        spaceAfter=18,
    )

    h2_style = ParagraphStyle(
        "BlogHeading2",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=17,
        leading=21,
        spaceBefore=14,
        spaceAfter=8,
    )

    h3_style = ParagraphStyle(
        "BlogHeading3",
        parent=styles["Heading3"],
        fontName="Helvetica-Bold",
        fontSize=14,
        leading=18,
        spaceBefore=12,
        spaceAfter=6,
    )

    h4_style = ParagraphStyle(
        "BlogHeading4",
        parent=styles["Heading4"],
        fontName="Helvetica-Bold",
        fontSize=12,
        leading=15,
        spaceBefore=10,
        spaceAfter=5,
    )

    body_style = ParagraphStyle(
        "BlogBody",
        parent=styles["BodyText"],
        fontName="Helvetica",
        fontSize=10.5,
        leading=16,
        spaceAfter=8,
    )

    bullet_style = ParagraphStyle(
        "BlogBullet",
        parent=body_style,
        leftIndent=18,
        firstLineIndent=0,
        spaceAfter=4,
    )

    quote_style = ParagraphStyle(
        "BlogQuote",
        parent=body_style,
        leftIndent=24,
        rightIndent=12,
        fontName="Helvetica-Oblique",
        spaceBefore=5,
        spaceAfter=8,
    )

    code_style = ParagraphStyle(
        "BlogCode",
        parent=styles["Code"],
        fontName="Courier",
        fontSize=8.5,
        leading=12,
        leftIndent=8,
        rightIndent=8,
        spaceBefore=6,
        spaceAfter=8,
    )

    # --------------------------------------------------------
    # Inline Markdown → ReportLab markup
    # --------------------------------------------------------

    def format_inline(text: str) -> str:
        """
        Convert basic Markdown inline formatting into
        ReportLab-compatible XML markup.
        """

        # Escape XML-sensitive characters first.
        text = escape(text)

        # Inline code.
        text = re.sub(
            r"`([^`]+)`",
            r'<font name="Courier">\1</font>',
            text,
        )

        # Bold.
        text = re.sub(
            r"\*\*(.*?)\*\*",
            r"<b>\1</b>",
            text,
        )

        text = re.sub(
            r"__(.*?)__",
            r"<b>\1</b>",
            text,
        )

        # Italic.
        text = re.sub(
            r"\*(.*?)\*",
            r"<i>\1</i>",
            text,
        )

        text = re.sub(
            r"_(.*?)_",
            r"<i>\1</i>",
            text,
        )

        # Markdown links.
        text = re.sub(
            r"\[([^\]]+)\]\(([^)]+)\)",
            r'<link href="\2" color="blue">\1</link>',
            text,
        )

        return text

    # --------------------------------------------------------
    # Build PDF story
    # --------------------------------------------------------

    story = []

    lines = markdown_content.splitlines()

    inside_code_block = False
    code_lines = []

    bullet_items = []
    numbered_items = []

    def flush_bullets():
        if not bullet_items:
            return

        items = [
            ListItem(
                Paragraph(
                    format_inline(item),
                    bullet_style,
                )
            )
            for item in bullet_items
        ]

        story.append(
            ListFlowable(
                items,
                bulletType="bullet",
                leftIndent=18,
                bulletFontName="Helvetica",
                bulletFontSize=8,
            )
        )

        story.append(
            Spacer(1, 5)
        )

        bullet_items.clear()

    def flush_numbered():
        if not numbered_items:
            return

        items = [
            ListItem(
                Paragraph(
                    format_inline(item),
                    bullet_style,
                )
            )
            for item in numbered_items
        ]

        story.append(
            ListFlowable(
                items,
                bulletType="1",
                start="1",
                leftIndent=22,
            )
        )

        story.append(
            Spacer(1, 5)
        )

        numbered_items.clear()

    for line in lines:

        stripped = line.strip()

        # ----------------------------------------------------
        # Code block
        # ----------------------------------------------------

        if stripped.startswith("```"):

            if not inside_code_block:

                flush_bullets()
                flush_numbered()

                inside_code_block = True
                code_lines = []

            else:

                inside_code_block = False

                code_text = "\n".join(
                    code_lines
                )

                story.append(
                    Preformatted(
                        code_text,
                        code_style,
                    )
                )

                code_lines = []

            continue

        if inside_code_block:

            code_lines.append(line)
            continue

        # ----------------------------------------------------
        # Empty line
        # ----------------------------------------------------

        if not stripped:

            flush_bullets()
            flush_numbered()

            story.append(
                Spacer(1, 3)
            )

            continue

        # ----------------------------------------------------
        # Bullet
        # ----------------------------------------------------

        bullet_match = re.match(
            r"^[-*+]\s+(.+)",
            stripped,
        )

        if bullet_match:

            flush_numbered()

            bullet_items.append(
                bullet_match.group(1)
            )

            continue

        # ----------------------------------------------------
        # Numbered list
        # ----------------------------------------------------

        numbered_match = re.match(
            r"^\d+\.\s+(.+)",
            stripped,
        )

        if numbered_match:

            flush_bullets()

            numbered_items.append(
                numbered_match.group(1)
            )

            continue

        # ----------------------------------------------------
        # Everything below this point is not a list.
        # Flush any pending list items first.
        # ----------------------------------------------------

        flush_bullets()
        flush_numbered()

        # ----------------------------------------------------
        # Heading 1
        # ----------------------------------------------------

        if re.match(
            r"^#\s+",
            stripped,
        ):

            heading = re.sub(
                r"^#\s+",
                "",
                stripped,
            )

            story.append(
                Paragraph(
                    format_inline(heading),
                    title_style,
                )
            )

            continue

        # ----------------------------------------------------
        # Heading 2
        # ----------------------------------------------------

        if re.match(
            r"^##\s+",
            stripped,
        ):

            heading = re.sub(
                r"^##\s+",
                "",
                stripped,
            )

            story.append(
                Paragraph(
                    format_inline(heading),
                    h2_style,
                )
            )

            continue

        # ----------------------------------------------------
        # Heading 3
        # ----------------------------------------------------

        if re.match(
            r"^###\s+",
            stripped,
        ):

            heading = re.sub(
                r"^###\s+",
                "",
                stripped,
            )

            story.append(
                Paragraph(
                    format_inline(heading),
                    h3_style,
                )
            )

            continue

        # ----------------------------------------------------
        # Heading 4–6
        # ----------------------------------------------------

        heading_match = re.match(
            r"^(#{4,6})\s+(.+)",
            stripped,
        )

        if heading_match:

            heading = heading_match.group(2)

            story.append(
                Paragraph(
                    format_inline(heading),
                    h4_style,
                )
            )

            continue

        # ----------------------------------------------------
        # Blockquote
        # ----------------------------------------------------

        quote_match = re.match(
            r"^>\s?(.*)",
            stripped,
        )

        if quote_match:

            story.append(
                Paragraph(
                    format_inline(
                        quote_match.group(1)
                    ),
                    quote_style,
                )
            )

            continue

        # ----------------------------------------------------
        # Horizontal rule
        # ----------------------------------------------------

        if re.match(
            r"^([-*_])(?:\s*\1){2,}$",
            stripped,
        ):

            story.append(
                Spacer(1, 5)
            )

            story.append(
                HRFlowable(
                    width="100%",
                    thickness=0.7,
                    spaceBefore=4,
                    spaceAfter=8,
                )
            )

            continue

        # ----------------------------------------------------
        # Normal paragraph
        # ----------------------------------------------------

        story.append(
            Paragraph(
                format_inline(stripped),
                body_style,
            )
        )

    # --------------------------------------------------------
    # Flush remaining lists
    # --------------------------------------------------------

    flush_bullets()
    flush_numbered()

    # --------------------------------------------------------
    # Build PDF
    # --------------------------------------------------------

    document.build(story)

    buffer.seek(0)

    filename = build_export_filename(
        markdown_content,
        "pdf",
    )

    return (
        buffer.getvalue(),
        filename,
    )