from typing import TypedDict, List, Annotated, Literal, Optional
import operator

from pydantic import BaseModel, Field

from .config import MIN_SECTIONS, MAX_SECTIONS, MAX_EVIDENCE_SOURCES


# ============================================================
# 1. PYDANTIC SCHEMAS
# ============================================================

class Task(BaseModel):
    """
    Represents one section/task of the blog.
    """

    id: int

    title: str

    goal: str = Field(
        ...,
        description=(
            "The single primary purpose of this section. "
            "It must be clearly distinct from the purpose of every other section."
        ),
    )

    bullets: List[str] = Field(
        ...,
        description=(
            "3–6 concrete pieces of information that are exclusively "
            "owned by this section. These should not duplicate facts, "
            "concepts, explanations, examples, or responsibilities "
            "assigned to another section."
        ),
    )

    target_words: int = Field(
        ...,
        description="Target word count for this section.",
    )

    section_type: Literal[
        "intro",
        "core",
        "examples",
        "checklist",
        "common_mistakes",
        "conclusion",
    ] = Field(
        ...,
        description="Type of the blog section.",
    )

    brief: str = Field(
        ...,
        description=(
            "A concise description of exactly what this section should "
            "explain. It must stay within this section's ownership boundary "
            "and must not develop topics assigned to other sections."
        ),
    )

    tags: List[str] = Field(
        default_factory=list,
        description="Important tags/topics for this section.",
    )

    requires_research: bool = Field(
        default=False,
        description="Whether this section requires fresh research.",
    )

    requires_citations: bool = Field(
        default=False,
        description="Whether outside-world claims need citations.",
    )

    requires_code: bool = Field(
        default=False,
        description="Whether this section must contain a code example.",
    )

    must_not_cover: List[str] = Field(
        default_factory=list,
        description=(
            "Topics, facts, concepts, examples, or content areas "
            "that belong to other sections and must not be developed "
            "in this section."
        ),
    )


class Plan(BaseModel):
    """
    Complete blog plan generated by the orchestrator.
    """

    blog_title: str

    audience: str = Field(
        description="Who this blog is made for.",
    )

    tone: str = Field(
        description=(
            "Writing tone, for example practical, crisp, "
            "technical, beginner-friendly, etc."
        ),
    )

    blog_kind: Literal[
        "tutorial",
        "news_roundup",
    ] = Field(
        default="tutorial",
        description="The overall type of the blog.",
    )

    constraints: List[str] = Field(
        default_factory=list,
        description="Important constraints that apply to the blog.",
    )

    tasks: List[Task] = Field(
        ...,
        min_length=MIN_SECTIONS,
        max_length=MAX_SECTIONS,
        description=(
            "Dynamically chosen blog sections/tasks. "
            "Must contain between 5 and 7 sections."
        ),
    )


class RouterDecision(BaseModel):
    """
    Decision produced by the routing node.
    """

    needs_research: bool

    mode: Literal[
        "closed_book",
        "hybrid",
        "open_book",
    ]

    queries: List[str] = Field(
        default_factory=list,
        max_length=10,
    )


class EvidenceItem(BaseModel):
    """
    One research source.
    """

    title: str

    url: str

    published_at: Optional[str] = None

    snippet: Optional[str] = None

    source: Optional[str] = None


class EvidencePack(BaseModel):
    """
    Collection of research sources.
    """

    evidence: List[EvidenceItem] = Field(
        default_factory=list,
        max_length=MAX_EVIDENCE_SOURCES,
    )


# ============================================================
# 2. LANGGRAPH STATE
# ============================================================

class ChatState(TypedDict):
    """
    Shared state used by the LangGraph workflow.
    """

    topic: str

    mode: str

    needs_research: bool

    queries: List[str]

    evidence: List[EvidenceItem]

    plan: Optional[Plan]

    sections: Annotated[
        List[tuple[int, str]],
        operator.add,
    ]

    final_md: str


class WorkerState(TypedDict):
    """
    State received by one dynamically created worker branch.

    Each worker receives exactly one planned Task, while the
    parent ChatState keeps the shared blog-generation state.
    """

    plan: Plan

    task: Task

    topic: str

    mode: str

    evidence: List[EvidenceItem]